/*
 * generated by Xtext
 */
package net.modelbased.ui.contentassist

import net.modelbased.ui.contentassist.AbstractConstraintMLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ConstraintMLProposalProvider extends AbstractConstraintMLProposalProvider {
}
