/*
 * generated by Xtext
 */
package net.modelbased;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConstraintMLRuntimeModule extends net.modelbased.AbstractConstraintMLRuntimeModule {

}
