from z3 import *
vM_names = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10', 'v11']
vMs = dict()
VM, (vM_v1, vM_v2, vM_v3, vM_v4, vM_v5, vM_v6, vM_v7, vM_v8, vM_v9, vM_v10, vM_v11) = EnumSort('VM', vM_names)
vmlit = [vM_v1, vM_v2, vM_v3, vM_v4, vM_v5, vM_v6, vM_v7, vM_v8, vM_v9, vM_v10, vM_v11]
objName = Function('vM_core', VM, IntSort()) 
pM_names = ['pm1', 'pm2', 'pm3', 'pm4', 'pm5', 'pm6']
pMs = dict()
PM, (pM_pm1, pM_pm2, pM_pm3, pM_pm4, pM_pm5, pM_pm6) = EnumSort('PM', pM_names)
pmlit = [pM_pm1, pM_pm2, pM_pm3, pM_pm4, pM_pm5, pM_pm6]

vM_core = Function('vM_core', VM, IntSort())
vM_mem = Function('vM_mem', VM, IntSort())
vM_bit64 = Function('vM_bit64', VM, BoolSort())
vM_frqt = Function('vM_frqt', VM, VM, BoolSort())
pM_hosting = Function('pM_hosting', PM, VM, BoolSort())
vM_plc = Function('vM_plc', VM, PM)
vM_syncPeak = Function('vM_syncPeak', VM, VM, BoolSort())
pM_near = Function('pM_near', PM, PM, BoolSort())
vM_backup = Function('vM_backup', VM, VM, BoolSort())
vM_stability = Function('vM_stability', VM, IntSort())
pM_bit64 = Function('pM_bit64', PM, BoolSort())
pM_mem = Function('pM_mem', PM, IntSort())
pM_tpLimit = Function('pM_tpLimit', PM, IntSort())
pM_stable = Function('pM_stable', PM, BoolSort())
pM_core = Function('pM_core', PM, IntSort())
vM_tp = Function('vM_tp', VM, IntSort())

goals = [
]
	
current = [
	(vM_core(vM_v1)) == (4),
	(vM_plc(vM_v1)) == (pM_pm1),
	(vM_core(vM_v2)) == (4),
	(vM_plc(vM_v2)) == (pM_pm1),
	(vM_core(vM_v3)) == (4),
	(vM_plc(vM_v3)) == (pM_pm2),
	(vM_core(vM_v4)) == (4),
	(vM_plc(vM_v4)) == (pM_pm2),
	(vM_core(vM_v5)) == (4),
	(vM_plc(vM_v5)) == (pM_pm2),
	(vM_core(vM_v6)) == (4),
	(vM_plc(vM_v6)) == (pM_pm3),
	(vM_core(vM_v7)) == (4),
	(vM_plc(vM_v7)) == (pM_pm3),
	(vM_core(vM_v8)) == (4),
	(vM_plc(vM_v8)) == (pM_pm4),
	(vM_core(vM_v9)) == (4),
	(vM_plc(vM_v9)) == (pM_pm5),
	(vM_core(vM_v10)) == (4),
	(vM_plc(vM_v10)) == (pM_pm5),
	(vM_core(vM_v11)) == (4),
	(vM_plc(vM_v11)) == (pM_pm2),
]

hard = [
	Or((vM_core(vM_v1)) == 1, (vM_core(vM_v1)) == 2, (vM_core(vM_v1)) == 4, (vM_core(vM_v1)) == 8),
	(vM_mem(vM_v1)) == (2),
	(vM_bit64(vM_v1)) == (False),
	(vM_frqt(vM_v1, vM_v1)) == False,
	(vM_frqt(vM_v1, vM_v2)) == False,
	(vM_frqt(vM_v1, vM_v3)) == False,
	(vM_frqt(vM_v1, vM_v4)) == False,
	(vM_frqt(vM_v1, vM_v5)) == False,
	(vM_frqt(vM_v1, vM_v6)) == False,
	(vM_frqt(vM_v1, vM_v7)) == False,
	(vM_frqt(vM_v1, vM_v8)) == False,
	(vM_frqt(vM_v1, vM_v9)) == False,
	(vM_frqt(vM_v1, vM_v10)) == False,
	(vM_frqt(vM_v1, vM_v11)) == False,
	(vM_syncPeak(vM_v1, vM_v1)) == False,
	(vM_syncPeak(vM_v1, vM_v2)) == False,
	(vM_syncPeak(vM_v1, vM_v3)) == False,
	(vM_syncPeak(vM_v1, vM_v4)) == True,
	(vM_syncPeak(vM_v1, vM_v5)) == False,
	(vM_syncPeak(vM_v1, vM_v6)) == True,
	(vM_syncPeak(vM_v1, vM_v7)) == False,
	(vM_syncPeak(vM_v1, vM_v8)) == False,
	(vM_syncPeak(vM_v1, vM_v9)) == False,
	(vM_syncPeak(vM_v1, vM_v10)) == False,
	(vM_syncPeak(vM_v1, vM_v11)) == False,
	(vM_backup(vM_v1, vM_v1)) == False,
	(vM_backup(vM_v1, vM_v2)) == False,
	(vM_backup(vM_v1, vM_v3)) == False,
	(vM_backup(vM_v1, vM_v4)) == False,
	(vM_backup(vM_v1, vM_v5)) == False,
	(vM_backup(vM_v1, vM_v6)) == False,
	(vM_backup(vM_v1, vM_v7)) == False,
	(vM_backup(vM_v1, vM_v8)) == False,
	(vM_backup(vM_v1, vM_v9)) == False,
	(vM_backup(vM_v1, vM_v10)) == False,
	(vM_backup(vM_v1, vM_v11)) == False,
	(vM_stability(vM_v1)) == (0),
	(vM_tp(vM_v1)) == (2),
	Or((vM_core(vM_v2)) == 1, (vM_core(vM_v2)) == 2, (vM_core(vM_v2)) == 4, (vM_core(vM_v2)) == 8),
	(vM_mem(vM_v2)) == (2),
	(vM_bit64(vM_v2)) == (False),
	(vM_frqt(vM_v2, vM_v1)) == False,
	(vM_frqt(vM_v2, vM_v2)) == False,
	(vM_frqt(vM_v2, vM_v3)) == False,
	(vM_frqt(vM_v2, vM_v4)) == False,
	(vM_frqt(vM_v2, vM_v5)) == False,
	(vM_frqt(vM_v2, vM_v6)) == False,
	(vM_frqt(vM_v2, vM_v7)) == False,
	(vM_frqt(vM_v2, vM_v8)) == False,
	(vM_frqt(vM_v2, vM_v9)) == False,
	(vM_frqt(vM_v2, vM_v10)) == False,
	(vM_frqt(vM_v2, vM_v11)) == False,
	(vM_syncPeak(vM_v2, vM_v1)) == False,
	(vM_syncPeak(vM_v2, vM_v2)) == False,
	(vM_syncPeak(vM_v2, vM_v3)) == False,
	(vM_syncPeak(vM_v2, vM_v4)) == False,
	(vM_syncPeak(vM_v2, vM_v5)) == False,
	(vM_syncPeak(vM_v2, vM_v6)) == False,
	(vM_syncPeak(vM_v2, vM_v7)) == False,
	(vM_syncPeak(vM_v2, vM_v8)) == False,
	(vM_syncPeak(vM_v2, vM_v9)) == False,
	(vM_syncPeak(vM_v2, vM_v10)) == False,
	(vM_syncPeak(vM_v2, vM_v11)) == False,
	(vM_backup(vM_v2, vM_v1)) == False,
	(vM_backup(vM_v2, vM_v2)) == False,
	(vM_backup(vM_v2, vM_v3)) == True,
	(vM_backup(vM_v2, vM_v4)) == False,
	(vM_backup(vM_v2, vM_v5)) == False,
	(vM_backup(vM_v2, vM_v6)) == False,
	(vM_backup(vM_v2, vM_v7)) == False,
	(vM_backup(vM_v2, vM_v8)) == False,
	(vM_backup(vM_v2, vM_v9)) == False,
	(vM_backup(vM_v2, vM_v10)) == False,
	(vM_backup(vM_v2, vM_v11)) == False,
	(vM_stability(vM_v2)) == (0),
	(vM_tp(vM_v2)) == (2),
	Or((vM_core(vM_v3)) == 1, (vM_core(vM_v3)) == 2, (vM_core(vM_v3)) == 4, (vM_core(vM_v3)) == 8),
	(vM_mem(vM_v3)) == (1),
	(vM_bit64(vM_v3)) == (True),
	(vM_frqt(vM_v3, vM_v1)) == False,
	(vM_frqt(vM_v3, vM_v2)) == False,
	(vM_frqt(vM_v3, vM_v3)) == False,
	(vM_frqt(vM_v3, vM_v4)) == False,
	(vM_frqt(vM_v3, vM_v5)) == False,
	(vM_frqt(vM_v3, vM_v6)) == False,
	(vM_frqt(vM_v3, vM_v7)) == False,
	(vM_frqt(vM_v3, vM_v8)) == False,
	(vM_frqt(vM_v3, vM_v9)) == False,
	(vM_frqt(vM_v3, vM_v10)) == False,
	(vM_frqt(vM_v3, vM_v11)) == False,
	(vM_syncPeak(vM_v3, vM_v1)) == False,
	(vM_syncPeak(vM_v3, vM_v2)) == False,
	(vM_syncPeak(vM_v3, vM_v3)) == False,
	(vM_syncPeak(vM_v3, vM_v4)) == False,
	(vM_syncPeak(vM_v3, vM_v5)) == False,
	(vM_syncPeak(vM_v3, vM_v6)) == False,
	(vM_syncPeak(vM_v3, vM_v7)) == False,
	(vM_syncPeak(vM_v3, vM_v8)) == False,
	(vM_syncPeak(vM_v3, vM_v9)) == False,
	(vM_syncPeak(vM_v3, vM_v10)) == False,
	(vM_syncPeak(vM_v3, vM_v11)) == False,
	(vM_backup(vM_v3, vM_v1)) == False,
	(vM_backup(vM_v3, vM_v2)) == True,
	(vM_backup(vM_v3, vM_v3)) == False,
	(vM_backup(vM_v3, vM_v4)) == False,
	(vM_backup(vM_v3, vM_v5)) == False,
	(vM_backup(vM_v3, vM_v6)) == False,
	(vM_backup(vM_v3, vM_v7)) == False,
	(vM_backup(vM_v3, vM_v8)) == False,
	(vM_backup(vM_v3, vM_v9)) == False,
	(vM_backup(vM_v3, vM_v10)) == False,
	(vM_backup(vM_v3, vM_v11)) == False,
	(vM_stability(vM_v3)) == (0),
	(vM_tp(vM_v3)) == (3),
	Or((vM_core(vM_v4)) == 1, (vM_core(vM_v4)) == 2, (vM_core(vM_v4)) == 4, (vM_core(vM_v4)) == 8),
	(vM_mem(vM_v4)) == (3),
	(vM_bit64(vM_v4)) == (True),
	(vM_frqt(vM_v4, vM_v1)) == False,
	(vM_frqt(vM_v4, vM_v2)) == False,
	(vM_frqt(vM_v4, vM_v3)) == False,
	(vM_frqt(vM_v4, vM_v4)) == False,
	(vM_frqt(vM_v4, vM_v5)) == False,
	(vM_frqt(vM_v4, vM_v6)) == False,
	(vM_frqt(vM_v4, vM_v7)) == False,
	(vM_frqt(vM_v4, vM_v8)) == False,
	(vM_frqt(vM_v4, vM_v9)) == False,
	(vM_frqt(vM_v4, vM_v10)) == False,
	(vM_frqt(vM_v4, vM_v11)) == False,
	(vM_syncPeak(vM_v4, vM_v1)) == True,
	(vM_syncPeak(vM_v4, vM_v2)) == False,
	(vM_syncPeak(vM_v4, vM_v3)) == False,
	(vM_syncPeak(vM_v4, vM_v4)) == False,
	(vM_syncPeak(vM_v4, vM_v5)) == False,
	(vM_syncPeak(vM_v4, vM_v6)) == True,
	(vM_syncPeak(vM_v4, vM_v7)) == False,
	(vM_syncPeak(vM_v4, vM_v8)) == False,
	(vM_syncPeak(vM_v4, vM_v9)) == False,
	(vM_syncPeak(vM_v4, vM_v10)) == False,
	(vM_syncPeak(vM_v4, vM_v11)) == False,
	(vM_backup(vM_v4, vM_v1)) == False,
	(vM_backup(vM_v4, vM_v2)) == False,
	(vM_backup(vM_v4, vM_v3)) == False,
	(vM_backup(vM_v4, vM_v4)) == False,
	(vM_backup(vM_v4, vM_v5)) == False,
	(vM_backup(vM_v4, vM_v6)) == False,
	(vM_backup(vM_v4, vM_v7)) == False,
	(vM_backup(vM_v4, vM_v8)) == False,
	(vM_backup(vM_v4, vM_v9)) == False,
	(vM_backup(vM_v4, vM_v10)) == False,
	(vM_backup(vM_v4, vM_v11)) == False,
	(vM_stability(vM_v4)) == (0),
	(vM_tp(vM_v4)) == (3),
	Or((vM_core(vM_v5)) == 1, (vM_core(vM_v5)) == 2, (vM_core(vM_v5)) == 4, (vM_core(vM_v5)) == 8),
	(vM_mem(vM_v5)) == (6),
	(vM_bit64(vM_v5)) == (False),
	(vM_frqt(vM_v5, vM_v1)) == False,
	(vM_frqt(vM_v5, vM_v2)) == False,
	(vM_frqt(vM_v5, vM_v3)) == False,
	(vM_frqt(vM_v5, vM_v4)) == False,
	(vM_frqt(vM_v5, vM_v5)) == False,
	(vM_frqt(vM_v5, vM_v6)) == True,
	(vM_frqt(vM_v5, vM_v7)) == False,
	(vM_frqt(vM_v5, vM_v8)) == False,
	(vM_frqt(vM_v5, vM_v9)) == False,
	(vM_frqt(vM_v5, vM_v10)) == False,
	(vM_frqt(vM_v5, vM_v11)) == False,
	(vM_syncPeak(vM_v5, vM_v1)) == False,
	(vM_syncPeak(vM_v5, vM_v2)) == False,
	(vM_syncPeak(vM_v5, vM_v3)) == False,
	(vM_syncPeak(vM_v5, vM_v4)) == False,
	(vM_syncPeak(vM_v5, vM_v5)) == False,
	(vM_syncPeak(vM_v5, vM_v6)) == False,
	(vM_syncPeak(vM_v5, vM_v7)) == False,
	(vM_syncPeak(vM_v5, vM_v8)) == False,
	(vM_syncPeak(vM_v5, vM_v9)) == False,
	(vM_syncPeak(vM_v5, vM_v10)) == False,
	(vM_syncPeak(vM_v5, vM_v11)) == False,
	(vM_backup(vM_v5, vM_v1)) == False,
	(vM_backup(vM_v5, vM_v2)) == False,
	(vM_backup(vM_v5, vM_v3)) == False,
	(vM_backup(vM_v5, vM_v4)) == False,
	(vM_backup(vM_v5, vM_v5)) == False,
	(vM_backup(vM_v5, vM_v6)) == False,
	(vM_backup(vM_v5, vM_v7)) == False,
	(vM_backup(vM_v5, vM_v8)) == False,
	(vM_backup(vM_v5, vM_v9)) == False,
	(vM_backup(vM_v5, vM_v10)) == False,
	(vM_backup(vM_v5, vM_v11)) == False,
	(vM_stability(vM_v5)) == (0),
	(vM_tp(vM_v5)) == (2),
	Or((vM_core(vM_v6)) == 1, (vM_core(vM_v6)) == 2, (vM_core(vM_v6)) == 4, (vM_core(vM_v6)) == 8),
	(vM_mem(vM_v6)) == (2),
	(vM_bit64(vM_v6)) == (False),
	(vM_frqt(vM_v6, vM_v1)) == False,
	(vM_frqt(vM_v6, vM_v2)) == False,
	(vM_frqt(vM_v6, vM_v3)) == False,
	(vM_frqt(vM_v6, vM_v4)) == False,
	(vM_frqt(vM_v6, vM_v5)) == True,
	(vM_frqt(vM_v6, vM_v6)) == False,
	(vM_frqt(vM_v6, vM_v7)) == False,
	(vM_frqt(vM_v6, vM_v8)) == False,
	(vM_frqt(vM_v6, vM_v9)) == True,
	(vM_frqt(vM_v6, vM_v10)) == False,
	(vM_frqt(vM_v6, vM_v11)) == False,
	(vM_syncPeak(vM_v6, vM_v1)) == True,
	(vM_syncPeak(vM_v6, vM_v2)) == False,
	(vM_syncPeak(vM_v6, vM_v3)) == False,
	(vM_syncPeak(vM_v6, vM_v4)) == True,
	(vM_syncPeak(vM_v6, vM_v5)) == False,
	(vM_syncPeak(vM_v6, vM_v6)) == False,
	(vM_syncPeak(vM_v6, vM_v7)) == False,
	(vM_syncPeak(vM_v6, vM_v8)) == False,
	(vM_syncPeak(vM_v6, vM_v9)) == False,
	(vM_syncPeak(vM_v6, vM_v10)) == False,
	(vM_syncPeak(vM_v6, vM_v11)) == False,
	(vM_backup(vM_v6, vM_v1)) == False,
	(vM_backup(vM_v6, vM_v2)) == False,
	(vM_backup(vM_v6, vM_v3)) == False,
	(vM_backup(vM_v6, vM_v4)) == False,
	(vM_backup(vM_v6, vM_v5)) == False,
	(vM_backup(vM_v6, vM_v6)) == False,
	(vM_backup(vM_v6, vM_v7)) == False,
	(vM_backup(vM_v6, vM_v8)) == False,
	(vM_backup(vM_v6, vM_v9)) == False,
	(vM_backup(vM_v6, vM_v10)) == False,
	(vM_backup(vM_v6, vM_v11)) == False,
	(vM_stability(vM_v6)) == (1),
	(vM_tp(vM_v6)) == (1),
	Or((vM_core(vM_v7)) == 1, (vM_core(vM_v7)) == 2, (vM_core(vM_v7)) == 4, (vM_core(vM_v7)) == 8),
	(vM_mem(vM_v7)) == (2),
	(vM_bit64(vM_v7)) == (False),
	(vM_frqt(vM_v7, vM_v1)) == False,
	(vM_frqt(vM_v7, vM_v2)) == False,
	(vM_frqt(vM_v7, vM_v3)) == False,
	(vM_frqt(vM_v7, vM_v4)) == False,
	(vM_frqt(vM_v7, vM_v5)) == False,
	(vM_frqt(vM_v7, vM_v6)) == False,
	(vM_frqt(vM_v7, vM_v7)) == False,
	(vM_frqt(vM_v7, vM_v8)) == False,
	(vM_frqt(vM_v7, vM_v9)) == False,
	(vM_frqt(vM_v7, vM_v10)) == False,
	(vM_frqt(vM_v7, vM_v11)) == False,
	(vM_syncPeak(vM_v7, vM_v1)) == False,
	(vM_syncPeak(vM_v7, vM_v2)) == False,
	(vM_syncPeak(vM_v7, vM_v3)) == False,
	(vM_syncPeak(vM_v7, vM_v4)) == False,
	(vM_syncPeak(vM_v7, vM_v5)) == False,
	(vM_syncPeak(vM_v7, vM_v6)) == False,
	(vM_syncPeak(vM_v7, vM_v7)) == False,
	(vM_syncPeak(vM_v7, vM_v8)) == False,
	(vM_syncPeak(vM_v7, vM_v9)) == False,
	(vM_syncPeak(vM_v7, vM_v10)) == False,
	(vM_syncPeak(vM_v7, vM_v11)) == False,
	(vM_backup(vM_v7, vM_v1)) == False,
	(vM_backup(vM_v7, vM_v2)) == False,
	(vM_backup(vM_v7, vM_v3)) == False,
	(vM_backup(vM_v7, vM_v4)) == False,
	(vM_backup(vM_v7, vM_v5)) == False,
	(vM_backup(vM_v7, vM_v6)) == False,
	(vM_backup(vM_v7, vM_v7)) == False,
	(vM_backup(vM_v7, vM_v8)) == False,
	(vM_backup(vM_v7, vM_v9)) == False,
	(vM_backup(vM_v7, vM_v10)) == False,
	(vM_backup(vM_v7, vM_v11)) == False,
	(vM_stability(vM_v7)) == (1),
	(vM_tp(vM_v7)) == (2),
	Or((vM_core(vM_v8)) == 1, (vM_core(vM_v8)) == 2, (vM_core(vM_v8)) == 4, (vM_core(vM_v8)) == 8),
	(vM_mem(vM_v8)) == (1),
	(vM_bit64(vM_v8)) == (False),
	(vM_frqt(vM_v8, vM_v1)) == False,
	(vM_frqt(vM_v8, vM_v2)) == False,
	(vM_frqt(vM_v8, vM_v3)) == False,
	(vM_frqt(vM_v8, vM_v4)) == False,
	(vM_frqt(vM_v8, vM_v5)) == False,
	(vM_frqt(vM_v8, vM_v6)) == False,
	(vM_frqt(vM_v8, vM_v7)) == False,
	(vM_frqt(vM_v8, vM_v8)) == False,
	(vM_frqt(vM_v8, vM_v9)) == False,
	(vM_frqt(vM_v8, vM_v10)) == False,
	(vM_frqt(vM_v8, vM_v11)) == False,
	(vM_syncPeak(vM_v8, vM_v1)) == False,
	(vM_syncPeak(vM_v8, vM_v2)) == False,
	(vM_syncPeak(vM_v8, vM_v3)) == False,
	(vM_syncPeak(vM_v8, vM_v4)) == False,
	(vM_syncPeak(vM_v8, vM_v5)) == False,
	(vM_syncPeak(vM_v8, vM_v6)) == False,
	(vM_syncPeak(vM_v8, vM_v7)) == False,
	(vM_syncPeak(vM_v8, vM_v8)) == False,
	(vM_syncPeak(vM_v8, vM_v9)) == False,
	(vM_syncPeak(vM_v8, vM_v10)) == False,
	(vM_syncPeak(vM_v8, vM_v11)) == False,
	(vM_backup(vM_v8, vM_v1)) == False,
	(vM_backup(vM_v8, vM_v2)) == False,
	(vM_backup(vM_v8, vM_v3)) == False,
	(vM_backup(vM_v8, vM_v4)) == False,
	(vM_backup(vM_v8, vM_v5)) == False,
	(vM_backup(vM_v8, vM_v6)) == False,
	(vM_backup(vM_v8, vM_v7)) == False,
	(vM_backup(vM_v8, vM_v8)) == False,
	(vM_backup(vM_v8, vM_v9)) == True,
	(vM_backup(vM_v8, vM_v10)) == False,
	(vM_backup(vM_v8, vM_v11)) == False,
	(vM_stability(vM_v8)) == (0),
	(vM_tp(vM_v8)) == (10),
	Or((vM_core(vM_v9)) == 1, (vM_core(vM_v9)) == 2, (vM_core(vM_v9)) == 4, (vM_core(vM_v9)) == 8),
	(vM_mem(vM_v9)) == (1),
	(vM_bit64(vM_v9)) == (False),
	(vM_frqt(vM_v9, vM_v1)) == False,
	(vM_frqt(vM_v9, vM_v2)) == False,
	(vM_frqt(vM_v9, vM_v3)) == False,
	(vM_frqt(vM_v9, vM_v4)) == False,
	(vM_frqt(vM_v9, vM_v5)) == False,
	(vM_frqt(vM_v9, vM_v6)) == True,
	(vM_frqt(vM_v9, vM_v7)) == False,
	(vM_frqt(vM_v9, vM_v8)) == False,
	(vM_frqt(vM_v9, vM_v9)) == False,
	(vM_frqt(vM_v9, vM_v10)) == True,
	(vM_frqt(vM_v9, vM_v11)) == False,
	(vM_syncPeak(vM_v9, vM_v1)) == False,
	(vM_syncPeak(vM_v9, vM_v2)) == False,
	(vM_syncPeak(vM_v9, vM_v3)) == False,
	(vM_syncPeak(vM_v9, vM_v4)) == False,
	(vM_syncPeak(vM_v9, vM_v5)) == False,
	(vM_syncPeak(vM_v9, vM_v6)) == False,
	(vM_syncPeak(vM_v9, vM_v7)) == False,
	(vM_syncPeak(vM_v9, vM_v8)) == False,
	(vM_syncPeak(vM_v9, vM_v9)) == False,
	(vM_syncPeak(vM_v9, vM_v10)) == False,
	(vM_syncPeak(vM_v9, vM_v11)) == False,
	(vM_backup(vM_v9, vM_v1)) == False,
	(vM_backup(vM_v9, vM_v2)) == False,
	(vM_backup(vM_v9, vM_v3)) == False,
	(vM_backup(vM_v9, vM_v4)) == False,
	(vM_backup(vM_v9, vM_v5)) == False,
	(vM_backup(vM_v9, vM_v6)) == False,
	(vM_backup(vM_v9, vM_v7)) == False,
	(vM_backup(vM_v9, vM_v8)) == True,
	(vM_backup(vM_v9, vM_v9)) == False,
	(vM_backup(vM_v9, vM_v10)) == False,
	(vM_backup(vM_v9, vM_v11)) == False,
	(vM_stability(vM_v9)) == (0),
	(vM_tp(vM_v9)) == (1),
	Or((vM_core(vM_v10)) == 1, (vM_core(vM_v10)) == 2, (vM_core(vM_v10)) == 4, (vM_core(vM_v10)) == 8),
	(vM_mem(vM_v10)) == (2),
	(vM_bit64(vM_v10)) == (False),
	(vM_frqt(vM_v10, vM_v1)) == False,
	(vM_frqt(vM_v10, vM_v2)) == False,
	(vM_frqt(vM_v10, vM_v3)) == False,
	(vM_frqt(vM_v10, vM_v4)) == False,
	(vM_frqt(vM_v10, vM_v5)) == False,
	(vM_frqt(vM_v10, vM_v6)) == False,
	(vM_frqt(vM_v10, vM_v7)) == False,
	(vM_frqt(vM_v10, vM_v8)) == False,
	(vM_frqt(vM_v10, vM_v9)) == True,
	(vM_frqt(vM_v10, vM_v10)) == False,
	(vM_frqt(vM_v10, vM_v11)) == True,
	(vM_syncPeak(vM_v10, vM_v1)) == False,
	(vM_syncPeak(vM_v10, vM_v2)) == False,
	(vM_syncPeak(vM_v10, vM_v3)) == False,
	(vM_syncPeak(vM_v10, vM_v4)) == False,
	(vM_syncPeak(vM_v10, vM_v5)) == False,
	(vM_syncPeak(vM_v10, vM_v6)) == False,
	(vM_syncPeak(vM_v10, vM_v7)) == False,
	(vM_syncPeak(vM_v10, vM_v8)) == False,
	(vM_syncPeak(vM_v10, vM_v9)) == False,
	(vM_syncPeak(vM_v10, vM_v10)) == False,
	(vM_syncPeak(vM_v10, vM_v11)) == False,
	(vM_backup(vM_v10, vM_v1)) == False,
	(vM_backup(vM_v10, vM_v2)) == False,
	(vM_backup(vM_v10, vM_v3)) == False,
	(vM_backup(vM_v10, vM_v4)) == False,
	(vM_backup(vM_v10, vM_v5)) == False,
	(vM_backup(vM_v10, vM_v6)) == False,
	(vM_backup(vM_v10, vM_v7)) == False,
	(vM_backup(vM_v10, vM_v8)) == False,
	(vM_backup(vM_v10, vM_v9)) == False,
	(vM_backup(vM_v10, vM_v10)) == False,
	(vM_backup(vM_v10, vM_v11)) == False,
	(vM_stability(vM_v10)) == (1),
	(vM_tp(vM_v10)) == (1),
	Or((vM_core(vM_v11)) == 1, (vM_core(vM_v11)) == 2, (vM_core(vM_v11)) == 4, (vM_core(vM_v11)) == 8),
	(vM_mem(vM_v11)) == (5),
	(vM_bit64(vM_v11)) == (False),
	(vM_frqt(vM_v11, vM_v1)) == False,
	(vM_frqt(vM_v11, vM_v2)) == False,
	(vM_frqt(vM_v11, vM_v3)) == False,
	(vM_frqt(vM_v11, vM_v4)) == False,
	(vM_frqt(vM_v11, vM_v5)) == False,
	(vM_frqt(vM_v11, vM_v6)) == False,
	(vM_frqt(vM_v11, vM_v7)) == False,
	(vM_frqt(vM_v11, vM_v8)) == False,
	(vM_frqt(vM_v11, vM_v9)) == False,
	(vM_frqt(vM_v11, vM_v10)) == True,
	(vM_frqt(vM_v11, vM_v11)) == False,
	(vM_syncPeak(vM_v11, vM_v1)) == False,
	(vM_syncPeak(vM_v11, vM_v2)) == False,
	(vM_syncPeak(vM_v11, vM_v3)) == False,
	(vM_syncPeak(vM_v11, vM_v4)) == False,
	(vM_syncPeak(vM_v11, vM_v5)) == False,
	(vM_syncPeak(vM_v11, vM_v6)) == False,
	(vM_syncPeak(vM_v11, vM_v7)) == False,
	(vM_syncPeak(vM_v11, vM_v8)) == False,
	(vM_syncPeak(vM_v11, vM_v9)) == False,
	(vM_syncPeak(vM_v11, vM_v10)) == False,
	(vM_syncPeak(vM_v11, vM_v11)) == False,
	(vM_backup(vM_v11, vM_v1)) == False,
	(vM_backup(vM_v11, vM_v2)) == False,
	(vM_backup(vM_v11, vM_v3)) == False,
	(vM_backup(vM_v11, vM_v4)) == False,
	(vM_backup(vM_v11, vM_v5)) == False,
	(vM_backup(vM_v11, vM_v6)) == False,
	(vM_backup(vM_v11, vM_v7)) == False,
	(vM_backup(vM_v11, vM_v8)) == False,
	(vM_backup(vM_v11, vM_v9)) == False,
	(vM_backup(vM_v11, vM_v10)) == False,
	(vM_backup(vM_v11, vM_v11)) == False,
	(vM_stability(vM_v11)) == (0),
	(vM_tp(vM_v11)) == (1),
	(pM_hosting(pM_pm1, vM_v1)) == False,
	(pM_hosting(pM_pm1, vM_v2)) == False,
	(pM_hosting(pM_pm1, vM_v3)) == False,
	(pM_hosting(pM_pm1, vM_v4)) == False,
	(pM_hosting(pM_pm1, vM_v5)) == False,
	(pM_hosting(pM_pm1, vM_v6)) == False,
	(pM_hosting(pM_pm1, vM_v7)) == False,
	(pM_hosting(pM_pm1, vM_v8)) == False,
	(pM_hosting(pM_pm1, vM_v9)) == False,
	(pM_hosting(pM_pm1, vM_v10)) == False,
	(pM_hosting(pM_pm1, vM_v11)) == False,
	(pM_near(pM_pm1, pM_pm1)) == True,
	(pM_near(pM_pm1, pM_pm2)) == False,
	(pM_near(pM_pm1, pM_pm3)) == False,
	(pM_near(pM_pm1, pM_pm4)) == False,
	(pM_near(pM_pm1, pM_pm5)) == False,
	(pM_near(pM_pm1, pM_pm6)) == False,
	(pM_bit64(pM_pm1)) == (True),
	(pM_mem(pM_pm1)) == (4),
	(pM_tpLimit(pM_pm1)) == (10),
	(pM_stable(pM_pm1)) == (False),
	(pM_core(pM_pm1)) == (4),
	(pM_hosting(pM_pm2, vM_v1)) == False,
	(pM_hosting(pM_pm2, vM_v2)) == False,
	(pM_hosting(pM_pm2, vM_v3)) == False,
	(pM_hosting(pM_pm2, vM_v4)) == False,
	(pM_hosting(pM_pm2, vM_v5)) == False,
	(pM_hosting(pM_pm2, vM_v6)) == False,
	(pM_hosting(pM_pm2, vM_v7)) == False,
	(pM_hosting(pM_pm2, vM_v8)) == False,
	(pM_hosting(pM_pm2, vM_v9)) == False,
	(pM_hosting(pM_pm2, vM_v10)) == False,
	(pM_hosting(pM_pm2, vM_v11)) == False,
	(pM_near(pM_pm2, pM_pm1)) == False,
	(pM_near(pM_pm2, pM_pm2)) == True,
	(pM_near(pM_pm2, pM_pm3)) == True,
	(pM_near(pM_pm2, pM_pm4)) == False,
	(pM_near(pM_pm2, pM_pm5)) == False,
	(pM_near(pM_pm2, pM_pm6)) == False,
	(pM_bit64(pM_pm2)) == (True),
	(pM_mem(pM_pm2)) == (8),
	(pM_tpLimit(pM_pm2)) == (10),
	(pM_stable(pM_pm2)) == (False),
	(pM_core(pM_pm2)) == (8),
	(pM_hosting(pM_pm3, vM_v1)) == False,
	(pM_hosting(pM_pm3, vM_v2)) == False,
	(pM_hosting(pM_pm3, vM_v3)) == False,
	(pM_hosting(pM_pm3, vM_v4)) == False,
	(pM_hosting(pM_pm3, vM_v5)) == False,
	(pM_hosting(pM_pm3, vM_v6)) == False,
	(pM_hosting(pM_pm3, vM_v7)) == False,
	(pM_hosting(pM_pm3, vM_v8)) == False,
	(pM_hosting(pM_pm3, vM_v9)) == False,
	(pM_hosting(pM_pm3, vM_v10)) == False,
	(pM_hosting(pM_pm3, vM_v11)) == False,
	(pM_near(pM_pm3, pM_pm1)) == False,
	(pM_near(pM_pm3, pM_pm2)) == True,
	(pM_near(pM_pm3, pM_pm3)) == True,
	(pM_near(pM_pm3, pM_pm4)) == False,
	(pM_near(pM_pm3, pM_pm5)) == False,
	(pM_near(pM_pm3, pM_pm6)) == False,
	(pM_bit64(pM_pm3)) == (True),
	(pM_mem(pM_pm3)) == (16),
	(pM_tpLimit(pM_pm3)) == (5),
	(pM_stable(pM_pm3)) == (True),
	(pM_core(pM_pm3)) == (4),
	(pM_hosting(pM_pm4, vM_v1)) == False,
	(pM_hosting(pM_pm4, vM_v2)) == False,
	(pM_hosting(pM_pm4, vM_v3)) == False,
	(pM_hosting(pM_pm4, vM_v4)) == False,
	(pM_hosting(pM_pm4, vM_v5)) == False,
	(pM_hosting(pM_pm4, vM_v6)) == False,
	(pM_hosting(pM_pm4, vM_v7)) == False,
	(pM_hosting(pM_pm4, vM_v8)) == False,
	(pM_hosting(pM_pm4, vM_v9)) == False,
	(pM_hosting(pM_pm4, vM_v10)) == False,
	(pM_hosting(pM_pm4, vM_v11)) == False,
	(pM_near(pM_pm4, pM_pm1)) == False,
	(pM_near(pM_pm4, pM_pm2)) == False,
	(pM_near(pM_pm4, pM_pm3)) == False,
	(pM_near(pM_pm4, pM_pm4)) == True,
	(pM_near(pM_pm4, pM_pm5)) == True,
	(pM_near(pM_pm4, pM_pm6)) == False,
	(pM_bit64(pM_pm4)) == (False),
	(pM_mem(pM_pm4)) == (4),
	(pM_tpLimit(pM_pm4)) == (20),
	(pM_stable(pM_pm4)) == (False),
	(pM_core(pM_pm4)) == (4),
	(pM_hosting(pM_pm5, vM_v1)) == False,
	(pM_hosting(pM_pm5, vM_v2)) == False,
	(pM_hosting(pM_pm5, vM_v3)) == False,
	(pM_hosting(pM_pm5, vM_v4)) == False,
	(pM_hosting(pM_pm5, vM_v5)) == False,
	(pM_hosting(pM_pm5, vM_v6)) == False,
	(pM_hosting(pM_pm5, vM_v7)) == False,
	(pM_hosting(pM_pm5, vM_v8)) == False,
	(pM_hosting(pM_pm5, vM_v9)) == False,
	(pM_hosting(pM_pm5, vM_v10)) == False,
	(pM_hosting(pM_pm5, vM_v11)) == False,
	(pM_near(pM_pm5, pM_pm1)) == False,
	(pM_near(pM_pm5, pM_pm2)) == False,
	(pM_near(pM_pm5, pM_pm3)) == False,
	(pM_near(pM_pm5, pM_pm4)) == True,
	(pM_near(pM_pm5, pM_pm5)) == True,
	(pM_near(pM_pm5, pM_pm6)) == False,
	(pM_bit64(pM_pm5)) == (False),
	(pM_mem(pM_pm5)) == (4),
	(pM_tpLimit(pM_pm5)) == (10),
	(pM_stable(pM_pm5)) == (True),
	(pM_core(pM_pm5)) == (4),
	(pM_hosting(pM_pm6, vM_v1)) == False,
	(pM_hosting(pM_pm6, vM_v2)) == False,
	(pM_hosting(pM_pm6, vM_v3)) == False,
	(pM_hosting(pM_pm6, vM_v4)) == False,
	(pM_hosting(pM_pm6, vM_v5)) == False,
	(pM_hosting(pM_pm6, vM_v6)) == False,
	(pM_hosting(pM_pm6, vM_v7)) == False,
	(pM_hosting(pM_pm6, vM_v8)) == False,
	(pM_hosting(pM_pm6, vM_v9)) == False,
	(pM_hosting(pM_pm6, vM_v10)) == False,
	(pM_hosting(pM_pm6, vM_v11)) == False,
	(pM_near(pM_pm6, pM_pm1)) == False,
	(pM_near(pM_pm6, pM_pm2)) == False,
	(pM_near(pM_pm6, pM_pm3)) == False,
	(pM_near(pM_pm6, pM_pm4)) == False,
	(pM_near(pM_pm6, pM_pm5)) == False,
	(pM_near(pM_pm6, pM_pm6)) == False,
	(pM_bit64(pM_pm6)) == (True),
	(pM_mem(pM_pm6)) == (50),
	(pM_tpLimit(pM_pm6)) == (40),
	(pM_stable(pM_pm6)) == (True),
	(pM_core(pM_pm6)) == (8),
]

weights = [20, 20, 20, 20, 20, 10, 20, 30, 20, 60, 20, 20, 20, 20, 20, 10, 20, 10, 20, 20, 20, 50]

deps = [(0,0), (6,0), (0,2), (6,2), (1,4), (7,4), (1,6), (7,6), (1,8), (7,8), (2,10), (8,10), (2,12), (8,12), (3,14), (9,14), (4,16), (10,16), (4,18), (10,18), (1,20), (7,20)]

