/*
 * generated by Xtext
 */
package net.modelbased.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import net.modelbased.ui.internal.ConstraintMLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConstraintMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConstraintMLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConstraintMLActivator.getInstance().getInjector(ConstraintMLActivator.NET_MODELBASED_CONSTRAINTML);
	}
	
}
