/*
 * generated by Xtext
 */
package net.modelbased.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConstraintMLUiModule extends net.modelbased.ui.AbstractConstraintMLUiModule {
	public ConstraintMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
