from z3 import *
pM_names = ['pm1', 'pm2', 'pm3', 'pm4', 'pm5', 'pm6', 'pm7', 'pm8', 'pm9', 'pm10']
pMs = dict()
PM, (pM_pm1, pM_pm2, pM_pm3, pM_pm4, pM_pm5, pM_pm6, pM_pm7, pM_pm8, pM_pm9, pM_pm10) = EnumSort('PM', pM_names)
vM_names = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v12', 'v13', 'v14', 'v15', 'v16', 'v17', 'v20']
vMs = dict()
VM, (vM_v1, vM_v2, vM_v3, vM_v4, vM_v5, vM_v6, vM_v7, vM_v8, vM_v12, vM_v13, vM_v14, vM_v15, vM_v16, vM_v17, vM_v20) = EnumSort('VM', vM_names)
objName = Function('vM_core', VM, IntSort()) 


vmlit = [vM_v1, vM_v2, vM_v3, vM_v4, vM_v5, vM_v6, vM_v7, vM_v8, vM_v12, vM_v13, vM_v14, vM_v15, vM_v16, vM_v17, vM_v20]
pmlit = [pM_pm1, pM_pm2, pM_pm3, pM_pm4, pM_pm5, pM_pm6, pM_pm7, pM_pm8, pM_pm9, pM_pm10]

vM_stability = Function('vM_stability', VM, IntSort())
pM_near = Function('pM_near', PM, PM, BoolSort())
pM_bit64 = Function('pM_bit64', PM, BoolSort())
vM_core = Function('vM_core', VM, IntSort())
vM_frqt = Function('vM_frqt', VM, VM, BoolSort())
vM_mem = Function('vM_mem', VM, IntSort())
vM_backup = Function('vM_backup', VM, VM, BoolSort())
pM_tpLimit = Function('pM_tpLimit', PM, IntSort())
vM_tp = Function('vM_tp', VM, IntSort())
vM_plc = Function('vM_plc', VM, PM)
pM_mem = Function('pM_mem', PM, IntSort())
pM_stable = Function('pM_stable', PM, BoolSort())
vM_bit64 = Function('vM_bit64', VM, BoolSort())
vM_syncPeak = Function('vM_syncPeak', VM, VM, BoolSort())
pM_core = Function('pM_core', PM, IntSort())
pM_hosting = Function('pM_hosting', PM, VM, BoolSort())

goals = [
]
	
current = [
	(vM_core(vM_v1)) == (4),
	(vM_plc(vM_v1)) == (pM_pm1),
	(vM_core(vM_v2)) == (4),
	(vM_plc(vM_v2)) == (pM_pm1),
	(vM_core(vM_v3)) == (4),
	(vM_plc(vM_v3)) == (pM_pm2),
	(vM_core(vM_v4)) == (4),
	(vM_plc(vM_v4)) == (pM_pm2),
	(vM_core(vM_v5)) == (4),
	(vM_plc(vM_v5)) == (pM_pm2),
	(vM_core(vM_v6)) == (4),
	(vM_plc(vM_v6)) == (pM_pm3),
	(vM_core(vM_v7)) == (4),
	(vM_plc(vM_v7)) == (pM_pm3),
	(vM_core(vM_v8)) == (4),
	(vM_plc(vM_v8)) == (pM_pm4),
	(vM_core(vM_v12)) == (4),
	(vM_plc(vM_v12)) == (pM_pm6),
	(vM_core(vM_v13)) == (4),
	(vM_plc(vM_v13)) == (pM_pm7),
	(vM_core(vM_v14)) == (4),
	(vM_plc(vM_v14)) == (pM_pm7),
	(vM_core(vM_v15)) == (4),
	(vM_plc(vM_v15)) == (pM_pm7),
	(vM_core(vM_v16)) == (4),
	(vM_plc(vM_v16)) == (pM_pm8),
	(vM_core(vM_v17)) == (4),
	(vM_plc(vM_v17)) == (pM_pm8),
	(vM_core(vM_v20)) == (4),
	(vM_plc(vM_v20)) == (pM_pm10),
]

hard = [
	(vM_stability(vM_v1)) == (0),
	Or((vM_core(vM_v1)) == 1, (vM_core(vM_v1)) == 2, (vM_core(vM_v1)) == 4, (vM_core(vM_v1)) == 8),
	(vM_frqt(vM_v1, vM_v1)) == False,
	(vM_frqt(vM_v1, vM_v2)) == False,
	(vM_frqt(vM_v1, vM_v3)) == False,
	(vM_frqt(vM_v1, vM_v4)) == False,
	(vM_frqt(vM_v1, vM_v5)) == False,
	(vM_frqt(vM_v1, vM_v6)) == False,
	(vM_frqt(vM_v1, vM_v7)) == False,
	(vM_frqt(vM_v1, vM_v8)) == False,
	(vM_frqt(vM_v1, vM_v12)) == False,
	(vM_frqt(vM_v1, vM_v13)) == False,
	(vM_frqt(vM_v1, vM_v14)) == False,
	(vM_frqt(vM_v1, vM_v15)) == False,
	(vM_frqt(vM_v1, vM_v16)) == False,
	(vM_frqt(vM_v1, vM_v17)) == False,
	(vM_frqt(vM_v1, vM_v20)) == False,
	(vM_mem(vM_v1)) == (2),
	(vM_backup(vM_v1, vM_v1)) == False,
	(vM_backup(vM_v1, vM_v2)) == False,
	(vM_backup(vM_v1, vM_v3)) == False,
	(vM_backup(vM_v1, vM_v4)) == False,
	(vM_backup(vM_v1, vM_v5)) == False,
	(vM_backup(vM_v1, vM_v6)) == False,
	(vM_backup(vM_v1, vM_v7)) == False,
	(vM_backup(vM_v1, vM_v8)) == False,
	(vM_backup(vM_v1, vM_v12)) == False,
	(vM_backup(vM_v1, vM_v13)) == False,
	(vM_backup(vM_v1, vM_v14)) == False,
	(vM_backup(vM_v1, vM_v15)) == False,
	(vM_backup(vM_v1, vM_v16)) == False,
	(vM_backup(vM_v1, vM_v17)) == False,
	(vM_backup(vM_v1, vM_v20)) == False,
	(vM_tp(vM_v1)) == (2),
	(vM_bit64(vM_v1)) == (False),
	(vM_syncPeak(vM_v1, vM_v1)) == False,
	(vM_syncPeak(vM_v1, vM_v2)) == False,
	(vM_syncPeak(vM_v1, vM_v3)) == False,
	(vM_syncPeak(vM_v1, vM_v4)) == True,
	(vM_syncPeak(vM_v1, vM_v5)) == False,
	(vM_syncPeak(vM_v1, vM_v6)) == True,
	(vM_syncPeak(vM_v1, vM_v7)) == False,
	(vM_syncPeak(vM_v1, vM_v8)) == False,
	(vM_syncPeak(vM_v1, vM_v12)) == False,
	(vM_syncPeak(vM_v1, vM_v13)) == False,
	(vM_syncPeak(vM_v1, vM_v14)) == False,
	(vM_syncPeak(vM_v1, vM_v15)) == False,
	(vM_syncPeak(vM_v1, vM_v16)) == False,
	(vM_syncPeak(vM_v1, vM_v17)) == False,
	(vM_syncPeak(vM_v1, vM_v20)) == False,
	(vM_stability(vM_v2)) == (0),
	Or((vM_core(vM_v2)) == 1, (vM_core(vM_v2)) == 2, (vM_core(vM_v2)) == 4, (vM_core(vM_v2)) == 8),
	(vM_frqt(vM_v2, vM_v1)) == False,
	(vM_frqt(vM_v2, vM_v2)) == False,
	(vM_frqt(vM_v2, vM_v3)) == False,
	(vM_frqt(vM_v2, vM_v4)) == False,
	(vM_frqt(vM_v2, vM_v5)) == False,
	(vM_frqt(vM_v2, vM_v6)) == False,
	(vM_frqt(vM_v2, vM_v7)) == False,
	(vM_frqt(vM_v2, vM_v8)) == False,
	(vM_frqt(vM_v2, vM_v12)) == False,
	(vM_frqt(vM_v2, vM_v13)) == False,
	(vM_frqt(vM_v2, vM_v14)) == False,
	(vM_frqt(vM_v2, vM_v15)) == False,
	(vM_frqt(vM_v2, vM_v16)) == False,
	(vM_frqt(vM_v2, vM_v17)) == False,
	(vM_frqt(vM_v2, vM_v20)) == False,
	(vM_mem(vM_v2)) == (2),
	(vM_backup(vM_v2, vM_v1)) == False,
	(vM_backup(vM_v2, vM_v2)) == False,
	(vM_backup(vM_v2, vM_v3)) == True,
	(vM_backup(vM_v2, vM_v4)) == False,
	(vM_backup(vM_v2, vM_v5)) == False,
	(vM_backup(vM_v2, vM_v6)) == False,
	(vM_backup(vM_v2, vM_v7)) == False,
	(vM_backup(vM_v2, vM_v8)) == False,
	(vM_backup(vM_v2, vM_v12)) == False,
	(vM_backup(vM_v2, vM_v13)) == False,
	(vM_backup(vM_v2, vM_v14)) == False,
	(vM_backup(vM_v2, vM_v15)) == False,
	(vM_backup(vM_v2, vM_v16)) == False,
	(vM_backup(vM_v2, vM_v17)) == False,
	(vM_backup(vM_v2, vM_v20)) == False,
	(vM_tp(vM_v2)) == (2),
	(vM_bit64(vM_v2)) == (False),
	(vM_syncPeak(vM_v2, vM_v1)) == False,
	(vM_syncPeak(vM_v2, vM_v2)) == False,
	(vM_syncPeak(vM_v2, vM_v3)) == False,
	(vM_syncPeak(vM_v2, vM_v4)) == False,
	(vM_syncPeak(vM_v2, vM_v5)) == False,
	(vM_syncPeak(vM_v2, vM_v6)) == False,
	(vM_syncPeak(vM_v2, vM_v7)) == False,
	(vM_syncPeak(vM_v2, vM_v8)) == False,
	(vM_syncPeak(vM_v2, vM_v12)) == False,
	(vM_syncPeak(vM_v2, vM_v13)) == False,
	(vM_syncPeak(vM_v2, vM_v14)) == False,
	(vM_syncPeak(vM_v2, vM_v15)) == False,
	(vM_syncPeak(vM_v2, vM_v16)) == False,
	(vM_syncPeak(vM_v2, vM_v17)) == False,
	(vM_syncPeak(vM_v2, vM_v20)) == False,
	(vM_stability(vM_v3)) == (0),
	Or((vM_core(vM_v3)) == 1, (vM_core(vM_v3)) == 2, (vM_core(vM_v3)) == 4, (vM_core(vM_v3)) == 8),
	(vM_frqt(vM_v3, vM_v1)) == False,
	(vM_frqt(vM_v3, vM_v2)) == False,
	(vM_frqt(vM_v3, vM_v3)) == False,
	(vM_frqt(vM_v3, vM_v4)) == False,
	(vM_frqt(vM_v3, vM_v5)) == False,
	(vM_frqt(vM_v3, vM_v6)) == False,
	(vM_frqt(vM_v3, vM_v7)) == False,
	(vM_frqt(vM_v3, vM_v8)) == False,
	(vM_frqt(vM_v3, vM_v12)) == False,
	(vM_frqt(vM_v3, vM_v13)) == False,
	(vM_frqt(vM_v3, vM_v14)) == False,
	(vM_frqt(vM_v3, vM_v15)) == False,
	(vM_frqt(vM_v3, vM_v16)) == False,
	(vM_frqt(vM_v3, vM_v17)) == False,
	(vM_frqt(vM_v3, vM_v20)) == False,
	(vM_mem(vM_v3)) == (1),
	(vM_backup(vM_v3, vM_v1)) == False,
	(vM_backup(vM_v3, vM_v2)) == True,
	(vM_backup(vM_v3, vM_v3)) == False,
	(vM_backup(vM_v3, vM_v4)) == False,
	(vM_backup(vM_v3, vM_v5)) == False,
	(vM_backup(vM_v3, vM_v6)) == False,
	(vM_backup(vM_v3, vM_v7)) == False,
	(vM_backup(vM_v3, vM_v8)) == False,
	(vM_backup(vM_v3, vM_v12)) == False,
	(vM_backup(vM_v3, vM_v13)) == False,
	(vM_backup(vM_v3, vM_v14)) == False,
	(vM_backup(vM_v3, vM_v15)) == False,
	(vM_backup(vM_v3, vM_v16)) == False,
	(vM_backup(vM_v3, vM_v17)) == False,
	(vM_backup(vM_v3, vM_v20)) == False,
	(vM_tp(vM_v3)) == (3),
	(vM_bit64(vM_v3)) == (True),
	(vM_syncPeak(vM_v3, vM_v1)) == False,
	(vM_syncPeak(vM_v3, vM_v2)) == False,
	(vM_syncPeak(vM_v3, vM_v3)) == False,
	(vM_syncPeak(vM_v3, vM_v4)) == False,
	(vM_syncPeak(vM_v3, vM_v5)) == False,
	(vM_syncPeak(vM_v3, vM_v6)) == False,
	(vM_syncPeak(vM_v3, vM_v7)) == False,
	(vM_syncPeak(vM_v3, vM_v8)) == False,
	(vM_syncPeak(vM_v3, vM_v12)) == False,
	(vM_syncPeak(vM_v3, vM_v13)) == False,
	(vM_syncPeak(vM_v3, vM_v14)) == False,
	(vM_syncPeak(vM_v3, vM_v15)) == False,
	(vM_syncPeak(vM_v3, vM_v16)) == False,
	(vM_syncPeak(vM_v3, vM_v17)) == False,
	(vM_syncPeak(vM_v3, vM_v20)) == False,
	(vM_stability(vM_v4)) == (0),
	Or((vM_core(vM_v4)) == 1, (vM_core(vM_v4)) == 2, (vM_core(vM_v4)) == 4, (vM_core(vM_v4)) == 8),
	(vM_frqt(vM_v4, vM_v1)) == False,
	(vM_frqt(vM_v4, vM_v2)) == False,
	(vM_frqt(vM_v4, vM_v3)) == False,
	(vM_frqt(vM_v4, vM_v4)) == False,
	(vM_frqt(vM_v4, vM_v5)) == False,
	(vM_frqt(vM_v4, vM_v6)) == False,
	(vM_frqt(vM_v4, vM_v7)) == False,
	(vM_frqt(vM_v4, vM_v8)) == False,
	(vM_frqt(vM_v4, vM_v12)) == False,
	(vM_frqt(vM_v4, vM_v13)) == False,
	(vM_frqt(vM_v4, vM_v14)) == False,
	(vM_frqt(vM_v4, vM_v15)) == False,
	(vM_frqt(vM_v4, vM_v16)) == False,
	(vM_frqt(vM_v4, vM_v17)) == False,
	(vM_frqt(vM_v4, vM_v20)) == False,
	(vM_mem(vM_v4)) == (3),
	(vM_backup(vM_v4, vM_v1)) == False,
	(vM_backup(vM_v4, vM_v2)) == False,
	(vM_backup(vM_v4, vM_v3)) == False,
	(vM_backup(vM_v4, vM_v4)) == False,
	(vM_backup(vM_v4, vM_v5)) == False,
	(vM_backup(vM_v4, vM_v6)) == False,
	(vM_backup(vM_v4, vM_v7)) == False,
	(vM_backup(vM_v4, vM_v8)) == False,
	(vM_backup(vM_v4, vM_v12)) == False,
	(vM_backup(vM_v4, vM_v13)) == False,
	(vM_backup(vM_v4, vM_v14)) == False,
	(vM_backup(vM_v4, vM_v15)) == False,
	(vM_backup(vM_v4, vM_v16)) == False,
	(vM_backup(vM_v4, vM_v17)) == False,
	(vM_backup(vM_v4, vM_v20)) == False,
	(vM_tp(vM_v4)) == (3),
	(vM_bit64(vM_v4)) == (True),
	(vM_syncPeak(vM_v4, vM_v1)) == True,
	(vM_syncPeak(vM_v4, vM_v2)) == False,
	(vM_syncPeak(vM_v4, vM_v3)) == False,
	(vM_syncPeak(vM_v4, vM_v4)) == False,
	(vM_syncPeak(vM_v4, vM_v5)) == False,
	(vM_syncPeak(vM_v4, vM_v6)) == True,
	(vM_syncPeak(vM_v4, vM_v7)) == False,
	(vM_syncPeak(vM_v4, vM_v8)) == False,
	(vM_syncPeak(vM_v4, vM_v12)) == False,
	(vM_syncPeak(vM_v4, vM_v13)) == False,
	(vM_syncPeak(vM_v4, vM_v14)) == False,
	(vM_syncPeak(vM_v4, vM_v15)) == False,
	(vM_syncPeak(vM_v4, vM_v16)) == False,
	(vM_syncPeak(vM_v4, vM_v17)) == False,
	(vM_syncPeak(vM_v4, vM_v20)) == False,
	(vM_stability(vM_v5)) == (0),
	Or((vM_core(vM_v5)) == 1, (vM_core(vM_v5)) == 2, (vM_core(vM_v5)) == 4, (vM_core(vM_v5)) == 8),
	(vM_frqt(vM_v5, vM_v1)) == False,
	(vM_frqt(vM_v5, vM_v2)) == False,
	(vM_frqt(vM_v5, vM_v3)) == False,
	(vM_frqt(vM_v5, vM_v4)) == False,
	(vM_frqt(vM_v5, vM_v5)) == False,
	(vM_frqt(vM_v5, vM_v6)) == True,
	(vM_frqt(vM_v5, vM_v7)) == False,
	(vM_frqt(vM_v5, vM_v8)) == False,
	(vM_frqt(vM_v5, vM_v12)) == False,
	(vM_frqt(vM_v5, vM_v13)) == False,
	(vM_frqt(vM_v5, vM_v14)) == False,
	(vM_frqt(vM_v5, vM_v15)) == False,
	(vM_frqt(vM_v5, vM_v16)) == False,
	(vM_frqt(vM_v5, vM_v17)) == False,
	(vM_frqt(vM_v5, vM_v20)) == False,
	(vM_mem(vM_v5)) == (6),
	(vM_backup(vM_v5, vM_v1)) == False,
	(vM_backup(vM_v5, vM_v2)) == False,
	(vM_backup(vM_v5, vM_v3)) == False,
	(vM_backup(vM_v5, vM_v4)) == False,
	(vM_backup(vM_v5, vM_v5)) == False,
	(vM_backup(vM_v5, vM_v6)) == False,
	(vM_backup(vM_v5, vM_v7)) == False,
	(vM_backup(vM_v5, vM_v8)) == False,
	(vM_backup(vM_v5, vM_v12)) == False,
	(vM_backup(vM_v5, vM_v13)) == False,
	(vM_backup(vM_v5, vM_v14)) == False,
	(vM_backup(vM_v5, vM_v15)) == False,
	(vM_backup(vM_v5, vM_v16)) == False,
	(vM_backup(vM_v5, vM_v17)) == False,
	(vM_backup(vM_v5, vM_v20)) == False,
	(vM_tp(vM_v5)) == (2),
	(vM_bit64(vM_v5)) == (False),
	(vM_syncPeak(vM_v5, vM_v1)) == False,
	(vM_syncPeak(vM_v5, vM_v2)) == False,
	(vM_syncPeak(vM_v5, vM_v3)) == False,
	(vM_syncPeak(vM_v5, vM_v4)) == False,
	(vM_syncPeak(vM_v5, vM_v5)) == False,
	(vM_syncPeak(vM_v5, vM_v6)) == False,
	(vM_syncPeak(vM_v5, vM_v7)) == False,
	(vM_syncPeak(vM_v5, vM_v8)) == False,
	(vM_syncPeak(vM_v5, vM_v12)) == False,
	(vM_syncPeak(vM_v5, vM_v13)) == False,
	(vM_syncPeak(vM_v5, vM_v14)) == False,
	(vM_syncPeak(vM_v5, vM_v15)) == False,
	(vM_syncPeak(vM_v5, vM_v16)) == False,
	(vM_syncPeak(vM_v5, vM_v17)) == False,
	(vM_syncPeak(vM_v5, vM_v20)) == False,
	(vM_stability(vM_v6)) == (1),
	Or((vM_core(vM_v6)) == 1, (vM_core(vM_v6)) == 2, (vM_core(vM_v6)) == 4, (vM_core(vM_v6)) == 8),
	(vM_frqt(vM_v6, vM_v1)) == False,
	(vM_frqt(vM_v6, vM_v2)) == False,
	(vM_frqt(vM_v6, vM_v3)) == False,
	(vM_frqt(vM_v6, vM_v4)) == False,
	(vM_frqt(vM_v6, vM_v5)) == True,
	(vM_frqt(vM_v6, vM_v6)) == False,
	(vM_frqt(vM_v6, vM_v7)) == False,
	(vM_frqt(vM_v6, vM_v8)) == False,
	(vM_frqt(vM_v6, vM_v12)) == False,
	(vM_frqt(vM_v6, vM_v13)) == False,
	(vM_frqt(vM_v6, vM_v14)) == False,
	(vM_frqt(vM_v6, vM_v15)) == False,
	(vM_frqt(vM_v6, vM_v16)) == False,
	(vM_frqt(vM_v6, vM_v17)) == False,
	(vM_frqt(vM_v6, vM_v20)) == False,
	(vM_mem(vM_v6)) == (2),
	(vM_backup(vM_v6, vM_v1)) == False,
	(vM_backup(vM_v6, vM_v2)) == False,
	(vM_backup(vM_v6, vM_v3)) == False,
	(vM_backup(vM_v6, vM_v4)) == False,
	(vM_backup(vM_v6, vM_v5)) == False,
	(vM_backup(vM_v6, vM_v6)) == False,
	(vM_backup(vM_v6, vM_v7)) == False,
	(vM_backup(vM_v6, vM_v8)) == False,
	(vM_backup(vM_v6, vM_v12)) == False,
	(vM_backup(vM_v6, vM_v13)) == False,
	(vM_backup(vM_v6, vM_v14)) == False,
	(vM_backup(vM_v6, vM_v15)) == False,
	(vM_backup(vM_v6, vM_v16)) == False,
	(vM_backup(vM_v6, vM_v17)) == False,
	(vM_backup(vM_v6, vM_v20)) == False,
	(vM_tp(vM_v6)) == (1),
	(vM_bit64(vM_v6)) == (False),
	(vM_syncPeak(vM_v6, vM_v1)) == True,
	(vM_syncPeak(vM_v6, vM_v2)) == False,
	(vM_syncPeak(vM_v6, vM_v3)) == False,
	(vM_syncPeak(vM_v6, vM_v4)) == True,
	(vM_syncPeak(vM_v6, vM_v5)) == False,
	(vM_syncPeak(vM_v6, vM_v6)) == False,
	(vM_syncPeak(vM_v6, vM_v7)) == False,
	(vM_syncPeak(vM_v6, vM_v8)) == False,
	(vM_syncPeak(vM_v6, vM_v12)) == False,
	(vM_syncPeak(vM_v6, vM_v13)) == False,
	(vM_syncPeak(vM_v6, vM_v14)) == False,
	(vM_syncPeak(vM_v6, vM_v15)) == False,
	(vM_syncPeak(vM_v6, vM_v16)) == False,
	(vM_syncPeak(vM_v6, vM_v17)) == False,
	(vM_syncPeak(vM_v6, vM_v20)) == False,
	(vM_stability(vM_v7)) == (1),
	Or((vM_core(vM_v7)) == 1, (vM_core(vM_v7)) == 2, (vM_core(vM_v7)) == 4, (vM_core(vM_v7)) == 8),
	(vM_frqt(vM_v7, vM_v1)) == False,
	(vM_frqt(vM_v7, vM_v2)) == False,
	(vM_frqt(vM_v7, vM_v3)) == False,
	(vM_frqt(vM_v7, vM_v4)) == False,
	(vM_frqt(vM_v7, vM_v5)) == False,
	(vM_frqt(vM_v7, vM_v6)) == False,
	(vM_frqt(vM_v7, vM_v7)) == False,
	(vM_frqt(vM_v7, vM_v8)) == False,
	(vM_frqt(vM_v7, vM_v12)) == False,
	(vM_frqt(vM_v7, vM_v13)) == False,
	(vM_frqt(vM_v7, vM_v14)) == False,
	(vM_frqt(vM_v7, vM_v15)) == False,
	(vM_frqt(vM_v7, vM_v16)) == False,
	(vM_frqt(vM_v7, vM_v17)) == False,
	(vM_frqt(vM_v7, vM_v20)) == False,
	(vM_mem(vM_v7)) == (2),
	(vM_backup(vM_v7, vM_v1)) == False,
	(vM_backup(vM_v7, vM_v2)) == False,
	(vM_backup(vM_v7, vM_v3)) == False,
	(vM_backup(vM_v7, vM_v4)) == False,
	(vM_backup(vM_v7, vM_v5)) == False,
	(vM_backup(vM_v7, vM_v6)) == False,
	(vM_backup(vM_v7, vM_v7)) == False,
	(vM_backup(vM_v7, vM_v8)) == False,
	(vM_backup(vM_v7, vM_v12)) == False,
	(vM_backup(vM_v7, vM_v13)) == False,
	(vM_backup(vM_v7, vM_v14)) == False,
	(vM_backup(vM_v7, vM_v15)) == False,
	(vM_backup(vM_v7, vM_v16)) == False,
	(vM_backup(vM_v7, vM_v17)) == False,
	(vM_backup(vM_v7, vM_v20)) == False,
	(vM_tp(vM_v7)) == (2),
	(vM_bit64(vM_v7)) == (False),
	(vM_syncPeak(vM_v7, vM_v1)) == False,
	(vM_syncPeak(vM_v7, vM_v2)) == False,
	(vM_syncPeak(vM_v7, vM_v3)) == False,
	(vM_syncPeak(vM_v7, vM_v4)) == False,
	(vM_syncPeak(vM_v7, vM_v5)) == False,
	(vM_syncPeak(vM_v7, vM_v6)) == False,
	(vM_syncPeak(vM_v7, vM_v7)) == False,
	(vM_syncPeak(vM_v7, vM_v8)) == False,
	(vM_syncPeak(vM_v7, vM_v12)) == False,
	(vM_syncPeak(vM_v7, vM_v13)) == False,
	(vM_syncPeak(vM_v7, vM_v14)) == False,
	(vM_syncPeak(vM_v7, vM_v15)) == False,
	(vM_syncPeak(vM_v7, vM_v16)) == False,
	(vM_syncPeak(vM_v7, vM_v17)) == False,
	(vM_syncPeak(vM_v7, vM_v20)) == False,
	(vM_stability(vM_v8)) == (0),
	Or((vM_core(vM_v8)) == 1, (vM_core(vM_v8)) == 2, (vM_core(vM_v8)) == 4, (vM_core(vM_v8)) == 8),
	(vM_frqt(vM_v8, vM_v1)) == False,
	(vM_frqt(vM_v8, vM_v2)) == False,
	(vM_frqt(vM_v8, vM_v3)) == False,
	(vM_frqt(vM_v8, vM_v4)) == False,
	(vM_frqt(vM_v8, vM_v5)) == False,
	(vM_frqt(vM_v8, vM_v6)) == False,
	(vM_frqt(vM_v8, vM_v7)) == False,
	(vM_frqt(vM_v8, vM_v8)) == False,
	(vM_frqt(vM_v8, vM_v12)) == False,
	(vM_frqt(vM_v8, vM_v13)) == False,
	(vM_frqt(vM_v8, vM_v14)) == False,
	(vM_frqt(vM_v8, vM_v15)) == False,
	(vM_frqt(vM_v8, vM_v16)) == False,
	(vM_frqt(vM_v8, vM_v17)) == False,
	(vM_frqt(vM_v8, vM_v20)) == False,
	(vM_mem(vM_v8)) == (1),
	(vM_backup(vM_v8, vM_v1)) == False,
	(vM_backup(vM_v8, vM_v2)) == False,
	(vM_backup(vM_v8, vM_v3)) == False,
	(vM_backup(vM_v8, vM_v4)) == False,
	(vM_backup(vM_v8, vM_v5)) == False,
	(vM_backup(vM_v8, vM_v6)) == False,
	(vM_backup(vM_v8, vM_v7)) == False,
	(vM_backup(vM_v8, vM_v8)) == False,
	(vM_backup(vM_v8, vM_v12)) == False,
	(vM_backup(vM_v8, vM_v13)) == False,
	(vM_backup(vM_v8, vM_v14)) == False,
	(vM_backup(vM_v8, vM_v15)) == False,
	(vM_backup(vM_v8, vM_v16)) == False,
	(vM_backup(vM_v8, vM_v17)) == False,
	(vM_backup(vM_v8, vM_v20)) == False,
	(vM_tp(vM_v8)) == (10),
	(vM_bit64(vM_v8)) == (False),
	(vM_syncPeak(vM_v8, vM_v1)) == False,
	(vM_syncPeak(vM_v8, vM_v2)) == False,
	(vM_syncPeak(vM_v8, vM_v3)) == False,
	(vM_syncPeak(vM_v8, vM_v4)) == False,
	(vM_syncPeak(vM_v8, vM_v5)) == False,
	(vM_syncPeak(vM_v8, vM_v6)) == False,
	(vM_syncPeak(vM_v8, vM_v7)) == False,
	(vM_syncPeak(vM_v8, vM_v8)) == False,
	(vM_syncPeak(vM_v8, vM_v12)) == False,
	(vM_syncPeak(vM_v8, vM_v13)) == False,
	(vM_syncPeak(vM_v8, vM_v14)) == False,
	(vM_syncPeak(vM_v8, vM_v15)) == False,
	(vM_syncPeak(vM_v8, vM_v16)) == False,
	(vM_syncPeak(vM_v8, vM_v17)) == False,
	(vM_syncPeak(vM_v8, vM_v20)) == False,
	(vM_stability(vM_v12)) == (0),
	Or((vM_core(vM_v12)) == 1, (vM_core(vM_v12)) == 2, (vM_core(vM_v12)) == 4, (vM_core(vM_v12)) == 8),
	(vM_frqt(vM_v12, vM_v1)) == False,
	(vM_frqt(vM_v12, vM_v2)) == False,
	(vM_frqt(vM_v12, vM_v3)) == False,
	(vM_frqt(vM_v12, vM_v4)) == False,
	(vM_frqt(vM_v12, vM_v5)) == False,
	(vM_frqt(vM_v12, vM_v6)) == False,
	(vM_frqt(vM_v12, vM_v7)) == False,
	(vM_frqt(vM_v12, vM_v8)) == False,
	(vM_frqt(vM_v12, vM_v12)) == False,
	(vM_frqt(vM_v12, vM_v13)) == False,
	(vM_frqt(vM_v12, vM_v14)) == False,
	(vM_frqt(vM_v12, vM_v15)) == False,
	(vM_frqt(vM_v12, vM_v16)) == False,
	(vM_frqt(vM_v12, vM_v17)) == False,
	(vM_frqt(vM_v12, vM_v20)) == False,
	(vM_mem(vM_v12)) == (2),
	(vM_backup(vM_v12, vM_v1)) == False,
	(vM_backup(vM_v12, vM_v2)) == False,
	(vM_backup(vM_v12, vM_v3)) == False,
	(vM_backup(vM_v12, vM_v4)) == False,
	(vM_backup(vM_v12, vM_v5)) == False,
	(vM_backup(vM_v12, vM_v6)) == False,
	(vM_backup(vM_v12, vM_v7)) == False,
	(vM_backup(vM_v12, vM_v8)) == False,
	(vM_backup(vM_v12, vM_v12)) == False,
	(vM_backup(vM_v12, vM_v13)) == True,
	(vM_backup(vM_v12, vM_v14)) == False,
	(vM_backup(vM_v12, vM_v15)) == False,
	(vM_backup(vM_v12, vM_v16)) == False,
	(vM_backup(vM_v12, vM_v17)) == False,
	(vM_backup(vM_v12, vM_v20)) == False,
	(vM_tp(vM_v12)) == (2),
	(vM_bit64(vM_v12)) == (False),
	(vM_syncPeak(vM_v12, vM_v1)) == False,
	(vM_syncPeak(vM_v12, vM_v2)) == False,
	(vM_syncPeak(vM_v12, vM_v3)) == False,
	(vM_syncPeak(vM_v12, vM_v4)) == False,
	(vM_syncPeak(vM_v12, vM_v5)) == False,
	(vM_syncPeak(vM_v12, vM_v6)) == False,
	(vM_syncPeak(vM_v12, vM_v7)) == False,
	(vM_syncPeak(vM_v12, vM_v8)) == False,
	(vM_syncPeak(vM_v12, vM_v12)) == False,
	(vM_syncPeak(vM_v12, vM_v13)) == False,
	(vM_syncPeak(vM_v12, vM_v14)) == False,
	(vM_syncPeak(vM_v12, vM_v15)) == False,
	(vM_syncPeak(vM_v12, vM_v16)) == False,
	(vM_syncPeak(vM_v12, vM_v17)) == False,
	(vM_syncPeak(vM_v12, vM_v20)) == False,
	(vM_stability(vM_v13)) == (0),
	Or((vM_core(vM_v13)) == 1, (vM_core(vM_v13)) == 2, (vM_core(vM_v13)) == 4, (vM_core(vM_v13)) == 8),
	(vM_frqt(vM_v13, vM_v1)) == False,
	(vM_frqt(vM_v13, vM_v2)) == False,
	(vM_frqt(vM_v13, vM_v3)) == False,
	(vM_frqt(vM_v13, vM_v4)) == False,
	(vM_frqt(vM_v13, vM_v5)) == False,
	(vM_frqt(vM_v13, vM_v6)) == False,
	(vM_frqt(vM_v13, vM_v7)) == False,
	(vM_frqt(vM_v13, vM_v8)) == False,
	(vM_frqt(vM_v13, vM_v12)) == False,
	(vM_frqt(vM_v13, vM_v13)) == False,
	(vM_frqt(vM_v13, vM_v14)) == False,
	(vM_frqt(vM_v13, vM_v15)) == False,
	(vM_frqt(vM_v13, vM_v16)) == False,
	(vM_frqt(vM_v13, vM_v17)) == False,
	(vM_frqt(vM_v13, vM_v20)) == False,
	(vM_mem(vM_v13)) == (1),
	(vM_backup(vM_v13, vM_v1)) == False,
	(vM_backup(vM_v13, vM_v2)) == False,
	(vM_backup(vM_v13, vM_v3)) == False,
	(vM_backup(vM_v13, vM_v4)) == False,
	(vM_backup(vM_v13, vM_v5)) == False,
	(vM_backup(vM_v13, vM_v6)) == False,
	(vM_backup(vM_v13, vM_v7)) == False,
	(vM_backup(vM_v13, vM_v8)) == False,
	(vM_backup(vM_v13, vM_v12)) == True,
	(vM_backup(vM_v13, vM_v13)) == False,
	(vM_backup(vM_v13, vM_v14)) == False,
	(vM_backup(vM_v13, vM_v15)) == False,
	(vM_backup(vM_v13, vM_v16)) == False,
	(vM_backup(vM_v13, vM_v17)) == False,
	(vM_backup(vM_v13, vM_v20)) == False,
	(vM_tp(vM_v13)) == (3),
	(vM_bit64(vM_v13)) == (True),
	(vM_syncPeak(vM_v13, vM_v1)) == False,
	(vM_syncPeak(vM_v13, vM_v2)) == False,
	(vM_syncPeak(vM_v13, vM_v3)) == False,
	(vM_syncPeak(vM_v13, vM_v4)) == False,
	(vM_syncPeak(vM_v13, vM_v5)) == False,
	(vM_syncPeak(vM_v13, vM_v6)) == False,
	(vM_syncPeak(vM_v13, vM_v7)) == False,
	(vM_syncPeak(vM_v13, vM_v8)) == False,
	(vM_syncPeak(vM_v13, vM_v12)) == False,
	(vM_syncPeak(vM_v13, vM_v13)) == False,
	(vM_syncPeak(vM_v13, vM_v14)) == False,
	(vM_syncPeak(vM_v13, vM_v15)) == False,
	(vM_syncPeak(vM_v13, vM_v16)) == False,
	(vM_syncPeak(vM_v13, vM_v17)) == False,
	(vM_syncPeak(vM_v13, vM_v20)) == False,
	(vM_stability(vM_v14)) == (0),
	Or((vM_core(vM_v14)) == 1, (vM_core(vM_v14)) == 2, (vM_core(vM_v14)) == 4, (vM_core(vM_v14)) == 8),
	(vM_frqt(vM_v14, vM_v1)) == False,
	(vM_frqt(vM_v14, vM_v2)) == False,
	(vM_frqt(vM_v14, vM_v3)) == False,
	(vM_frqt(vM_v14, vM_v4)) == False,
	(vM_frqt(vM_v14, vM_v5)) == False,
	(vM_frqt(vM_v14, vM_v6)) == False,
	(vM_frqt(vM_v14, vM_v7)) == False,
	(vM_frqt(vM_v14, vM_v8)) == False,
	(vM_frqt(vM_v14, vM_v12)) == False,
	(vM_frqt(vM_v14, vM_v13)) == False,
	(vM_frqt(vM_v14, vM_v14)) == False,
	(vM_frqt(vM_v14, vM_v15)) == False,
	(vM_frqt(vM_v14, vM_v16)) == False,
	(vM_frqt(vM_v14, vM_v17)) == False,
	(vM_frqt(vM_v14, vM_v20)) == False,
	(vM_mem(vM_v14)) == (3),
	(vM_backup(vM_v14, vM_v1)) == False,
	(vM_backup(vM_v14, vM_v2)) == False,
	(vM_backup(vM_v14, vM_v3)) == False,
	(vM_backup(vM_v14, vM_v4)) == False,
	(vM_backup(vM_v14, vM_v5)) == False,
	(vM_backup(vM_v14, vM_v6)) == False,
	(vM_backup(vM_v14, vM_v7)) == False,
	(vM_backup(vM_v14, vM_v8)) == False,
	(vM_backup(vM_v14, vM_v12)) == False,
	(vM_backup(vM_v14, vM_v13)) == False,
	(vM_backup(vM_v14, vM_v14)) == False,
	(vM_backup(vM_v14, vM_v15)) == False,
	(vM_backup(vM_v14, vM_v16)) == False,
	(vM_backup(vM_v14, vM_v17)) == False,
	(vM_backup(vM_v14, vM_v20)) == False,
	(vM_tp(vM_v14)) == (3),
	(vM_bit64(vM_v14)) == (True),
	(vM_syncPeak(vM_v14, vM_v1)) == False,
	(vM_syncPeak(vM_v14, vM_v2)) == False,
	(vM_syncPeak(vM_v14, vM_v3)) == False,
	(vM_syncPeak(vM_v14, vM_v4)) == False,
	(vM_syncPeak(vM_v14, vM_v5)) == False,
	(vM_syncPeak(vM_v14, vM_v6)) == False,
	(vM_syncPeak(vM_v14, vM_v7)) == False,
	(vM_syncPeak(vM_v14, vM_v8)) == False,
	(vM_syncPeak(vM_v14, vM_v12)) == False,
	(vM_syncPeak(vM_v14, vM_v13)) == False,
	(vM_syncPeak(vM_v14, vM_v14)) == False,
	(vM_syncPeak(vM_v14, vM_v15)) == False,
	(vM_syncPeak(vM_v14, vM_v16)) == True,
	(vM_syncPeak(vM_v14, vM_v17)) == False,
	(vM_syncPeak(vM_v14, vM_v20)) == False,
	(vM_stability(vM_v15)) == (0),
	Or((vM_core(vM_v15)) == 1, (vM_core(vM_v15)) == 2, (vM_core(vM_v15)) == 4, (vM_core(vM_v15)) == 8),
	(vM_frqt(vM_v15, vM_v1)) == False,
	(vM_frqt(vM_v15, vM_v2)) == False,
	(vM_frqt(vM_v15, vM_v3)) == False,
	(vM_frqt(vM_v15, vM_v4)) == False,
	(vM_frqt(vM_v15, vM_v5)) == False,
	(vM_frqt(vM_v15, vM_v6)) == False,
	(vM_frqt(vM_v15, vM_v7)) == False,
	(vM_frqt(vM_v15, vM_v8)) == False,
	(vM_frqt(vM_v15, vM_v12)) == False,
	(vM_frqt(vM_v15, vM_v13)) == False,
	(vM_frqt(vM_v15, vM_v14)) == False,
	(vM_frqt(vM_v15, vM_v15)) == False,
	(vM_frqt(vM_v15, vM_v16)) == True,
	(vM_frqt(vM_v15, vM_v17)) == False,
	(vM_frqt(vM_v15, vM_v20)) == False,
	(vM_mem(vM_v15)) == (6),
	(vM_backup(vM_v15, vM_v1)) == False,
	(vM_backup(vM_v15, vM_v2)) == False,
	(vM_backup(vM_v15, vM_v3)) == False,
	(vM_backup(vM_v15, vM_v4)) == False,
	(vM_backup(vM_v15, vM_v5)) == False,
	(vM_backup(vM_v15, vM_v6)) == False,
	(vM_backup(vM_v15, vM_v7)) == False,
	(vM_backup(vM_v15, vM_v8)) == False,
	(vM_backup(vM_v15, vM_v12)) == False,
	(vM_backup(vM_v15, vM_v13)) == False,
	(vM_backup(vM_v15, vM_v14)) == False,
	(vM_backup(vM_v15, vM_v15)) == False,
	(vM_backup(vM_v15, vM_v16)) == False,
	(vM_backup(vM_v15, vM_v17)) == False,
	(vM_backup(vM_v15, vM_v20)) == False,
	(vM_tp(vM_v15)) == (2),
	(vM_bit64(vM_v15)) == (False),
	(vM_syncPeak(vM_v15, vM_v1)) == False,
	(vM_syncPeak(vM_v15, vM_v2)) == False,
	(vM_syncPeak(vM_v15, vM_v3)) == False,
	(vM_syncPeak(vM_v15, vM_v4)) == False,
	(vM_syncPeak(vM_v15, vM_v5)) == False,
	(vM_syncPeak(vM_v15, vM_v6)) == False,
	(vM_syncPeak(vM_v15, vM_v7)) == False,
	(vM_syncPeak(vM_v15, vM_v8)) == False,
	(vM_syncPeak(vM_v15, vM_v12)) == False,
	(vM_syncPeak(vM_v15, vM_v13)) == False,
	(vM_syncPeak(vM_v15, vM_v14)) == False,
	(vM_syncPeak(vM_v15, vM_v15)) == False,
	(vM_syncPeak(vM_v15, vM_v16)) == False,
	(vM_syncPeak(vM_v15, vM_v17)) == False,
	(vM_syncPeak(vM_v15, vM_v20)) == False,
	(vM_stability(vM_v16)) == (1),
	Or((vM_core(vM_v16)) == 1, (vM_core(vM_v16)) == 2, (vM_core(vM_v16)) == 4, (vM_core(vM_v16)) == 8),
	(vM_frqt(vM_v16, vM_v1)) == False,
	(vM_frqt(vM_v16, vM_v2)) == False,
	(vM_frqt(vM_v16, vM_v3)) == False,
	(vM_frqt(vM_v16, vM_v4)) == False,
	(vM_frqt(vM_v16, vM_v5)) == False,
	(vM_frqt(vM_v16, vM_v6)) == False,
	(vM_frqt(vM_v16, vM_v7)) == False,
	(vM_frqt(vM_v16, vM_v8)) == False,
	(vM_frqt(vM_v16, vM_v12)) == False,
	(vM_frqt(vM_v16, vM_v13)) == False,
	(vM_frqt(vM_v16, vM_v14)) == False,
	(vM_frqt(vM_v16, vM_v15)) == True,
	(vM_frqt(vM_v16, vM_v16)) == False,
	(vM_frqt(vM_v16, vM_v17)) == False,
	(vM_frqt(vM_v16, vM_v20)) == False,
	(vM_mem(vM_v16)) == (2),
	(vM_backup(vM_v16, vM_v1)) == False,
	(vM_backup(vM_v16, vM_v2)) == False,
	(vM_backup(vM_v16, vM_v3)) == False,
	(vM_backup(vM_v16, vM_v4)) == False,
	(vM_backup(vM_v16, vM_v5)) == False,
	(vM_backup(vM_v16, vM_v6)) == False,
	(vM_backup(vM_v16, vM_v7)) == False,
	(vM_backup(vM_v16, vM_v8)) == False,
	(vM_backup(vM_v16, vM_v12)) == False,
	(vM_backup(vM_v16, vM_v13)) == False,
	(vM_backup(vM_v16, vM_v14)) == False,
	(vM_backup(vM_v16, vM_v15)) == False,
	(vM_backup(vM_v16, vM_v16)) == False,
	(vM_backup(vM_v16, vM_v17)) == False,
	(vM_backup(vM_v16, vM_v20)) == False,
	(vM_tp(vM_v16)) == (1),
	(vM_bit64(vM_v16)) == (False),
	(vM_syncPeak(vM_v16, vM_v1)) == False,
	(vM_syncPeak(vM_v16, vM_v2)) == False,
	(vM_syncPeak(vM_v16, vM_v3)) == False,
	(vM_syncPeak(vM_v16, vM_v4)) == False,
	(vM_syncPeak(vM_v16, vM_v5)) == False,
	(vM_syncPeak(vM_v16, vM_v6)) == False,
	(vM_syncPeak(vM_v16, vM_v7)) == False,
	(vM_syncPeak(vM_v16, vM_v8)) == False,
	(vM_syncPeak(vM_v16, vM_v12)) == False,
	(vM_syncPeak(vM_v16, vM_v13)) == False,
	(vM_syncPeak(vM_v16, vM_v14)) == True,
	(vM_syncPeak(vM_v16, vM_v15)) == False,
	(vM_syncPeak(vM_v16, vM_v16)) == False,
	(vM_syncPeak(vM_v16, vM_v17)) == False,
	(vM_syncPeak(vM_v16, vM_v20)) == False,
	(vM_stability(vM_v17)) == (1),
	Or((vM_core(vM_v17)) == 1, (vM_core(vM_v17)) == 2, (vM_core(vM_v17)) == 4, (vM_core(vM_v17)) == 8),
	(vM_frqt(vM_v17, vM_v1)) == False,
	(vM_frqt(vM_v17, vM_v2)) == False,
	(vM_frqt(vM_v17, vM_v3)) == False,
	(vM_frqt(vM_v17, vM_v4)) == False,
	(vM_frqt(vM_v17, vM_v5)) == False,
	(vM_frqt(vM_v17, vM_v6)) == False,
	(vM_frqt(vM_v17, vM_v7)) == False,
	(vM_frqt(vM_v17, vM_v8)) == False,
	(vM_frqt(vM_v17, vM_v12)) == False,
	(vM_frqt(vM_v17, vM_v13)) == False,
	(vM_frqt(vM_v17, vM_v14)) == False,
	(vM_frqt(vM_v17, vM_v15)) == False,
	(vM_frqt(vM_v17, vM_v16)) == False,
	(vM_frqt(vM_v17, vM_v17)) == False,
	(vM_frqt(vM_v17, vM_v20)) == False,
	(vM_mem(vM_v17)) == (2),
	(vM_backup(vM_v17, vM_v1)) == False,
	(vM_backup(vM_v17, vM_v2)) == False,
	(vM_backup(vM_v17, vM_v3)) == False,
	(vM_backup(vM_v17, vM_v4)) == False,
	(vM_backup(vM_v17, vM_v5)) == False,
	(vM_backup(vM_v17, vM_v6)) == False,
	(vM_backup(vM_v17, vM_v7)) == False,
	(vM_backup(vM_v17, vM_v8)) == False,
	(vM_backup(vM_v17, vM_v12)) == False,
	(vM_backup(vM_v17, vM_v13)) == False,
	(vM_backup(vM_v17, vM_v14)) == False,
	(vM_backup(vM_v17, vM_v15)) == False,
	(vM_backup(vM_v17, vM_v16)) == False,
	(vM_backup(vM_v17, vM_v17)) == False,
	(vM_backup(vM_v17, vM_v20)) == False,
	(vM_tp(vM_v17)) == (2),
	(vM_bit64(vM_v17)) == (False),
	(vM_syncPeak(vM_v17, vM_v1)) == False,
	(vM_syncPeak(vM_v17, vM_v2)) == False,
	(vM_syncPeak(vM_v17, vM_v3)) == False,
	(vM_syncPeak(vM_v17, vM_v4)) == False,
	(vM_syncPeak(vM_v17, vM_v5)) == False,
	(vM_syncPeak(vM_v17, vM_v6)) == False,
	(vM_syncPeak(vM_v17, vM_v7)) == False,
	(vM_syncPeak(vM_v17, vM_v8)) == False,
	(vM_syncPeak(vM_v17, vM_v12)) == False,
	(vM_syncPeak(vM_v17, vM_v13)) == False,
	(vM_syncPeak(vM_v17, vM_v14)) == False,
	(vM_syncPeak(vM_v17, vM_v15)) == False,
	(vM_syncPeak(vM_v17, vM_v16)) == False,
	(vM_syncPeak(vM_v17, vM_v17)) == False,
	(vM_syncPeak(vM_v17, vM_v20)) == False,
	(vM_stability(vM_v20)) == (1),
	Or((vM_core(vM_v20)) == 1, (vM_core(vM_v20)) == 2, (vM_core(vM_v20)) == 4, (vM_core(vM_v20)) == 8),
	(vM_frqt(vM_v20, vM_v1)) == False,
	(vM_frqt(vM_v20, vM_v2)) == False,
	(vM_frqt(vM_v20, vM_v3)) == False,
	(vM_frqt(vM_v20, vM_v4)) == False,
	(vM_frqt(vM_v20, vM_v5)) == False,
	(vM_frqt(vM_v20, vM_v6)) == False,
	(vM_frqt(vM_v20, vM_v7)) == False,
	(vM_frqt(vM_v20, vM_v8)) == False,
	(vM_frqt(vM_v20, vM_v12)) == False,
	(vM_frqt(vM_v20, vM_v13)) == False,
	(vM_frqt(vM_v20, vM_v14)) == False,
	(vM_frqt(vM_v20, vM_v15)) == False,
	(vM_frqt(vM_v20, vM_v16)) == False,
	(vM_frqt(vM_v20, vM_v17)) == False,
	(vM_frqt(vM_v20, vM_v20)) == False,
	(vM_mem(vM_v20)) == (2),
	(vM_backup(vM_v20, vM_v1)) == False,
	(vM_backup(vM_v20, vM_v2)) == False,
	(vM_backup(vM_v20, vM_v3)) == False,
	(vM_backup(vM_v20, vM_v4)) == False,
	(vM_backup(vM_v20, vM_v5)) == False,
	(vM_backup(vM_v20, vM_v6)) == False,
	(vM_backup(vM_v20, vM_v7)) == False,
	(vM_backup(vM_v20, vM_v8)) == False,
	(vM_backup(vM_v20, vM_v12)) == False,
	(vM_backup(vM_v20, vM_v13)) == False,
	(vM_backup(vM_v20, vM_v14)) == False,
	(vM_backup(vM_v20, vM_v15)) == False,
	(vM_backup(vM_v20, vM_v16)) == False,
	(vM_backup(vM_v20, vM_v17)) == False,
	(vM_backup(vM_v20, vM_v20)) == False,
	(vM_tp(vM_v20)) == (1),
	(vM_bit64(vM_v20)) == (False),
	(vM_syncPeak(vM_v20, vM_v1)) == False,
	(vM_syncPeak(vM_v20, vM_v2)) == False,
	(vM_syncPeak(vM_v20, vM_v3)) == False,
	(vM_syncPeak(vM_v20, vM_v4)) == False,
	(vM_syncPeak(vM_v20, vM_v5)) == False,
	(vM_syncPeak(vM_v20, vM_v6)) == False,
	(vM_syncPeak(vM_v20, vM_v7)) == False,
	(vM_syncPeak(vM_v20, vM_v8)) == False,
	(vM_syncPeak(vM_v20, vM_v12)) == False,
	(vM_syncPeak(vM_v20, vM_v13)) == False,
	(vM_syncPeak(vM_v20, vM_v14)) == False,
	(vM_syncPeak(vM_v20, vM_v15)) == False,
	(vM_syncPeak(vM_v20, vM_v16)) == False,
	(vM_syncPeak(vM_v20, vM_v17)) == False,
	(vM_syncPeak(vM_v20, vM_v20)) == False,
	(pM_near(pM_pm1, pM_pm1)) == True,
	(pM_near(pM_pm1, pM_pm2)) == False,
	(pM_near(pM_pm1, pM_pm3)) == False,
	(pM_near(pM_pm1, pM_pm4)) == False,
	(pM_near(pM_pm1, pM_pm5)) == False,
	(pM_near(pM_pm1, pM_pm6)) == False,
	(pM_near(pM_pm1, pM_pm7)) == False,
	(pM_near(pM_pm1, pM_pm8)) == False,
	(pM_near(pM_pm1, pM_pm9)) == False,
	(pM_near(pM_pm1, pM_pm10)) == False,
	(pM_bit64(pM_pm1)) == (True),
	(pM_tpLimit(pM_pm1)) == (10),
	(pM_mem(pM_pm1)) == (4),
	(pM_stable(pM_pm1)) == (False),
	(pM_core(pM_pm1)) == (4),
	(pM_hosting(pM_pm1, vM_v1)) == False,
	(pM_hosting(pM_pm1, vM_v2)) == False,
	(pM_hosting(pM_pm1, vM_v3)) == False,
	(pM_hosting(pM_pm1, vM_v4)) == False,
	(pM_hosting(pM_pm1, vM_v5)) == False,
	(pM_hosting(pM_pm1, vM_v6)) == False,
	(pM_hosting(pM_pm1, vM_v7)) == False,
	(pM_hosting(pM_pm1, vM_v8)) == False,
	(pM_hosting(pM_pm1, vM_v12)) == False,
	(pM_hosting(pM_pm1, vM_v13)) == False,
	(pM_hosting(pM_pm1, vM_v14)) == False,
	(pM_hosting(pM_pm1, vM_v15)) == False,
	(pM_hosting(pM_pm1, vM_v16)) == False,
	(pM_hosting(pM_pm1, vM_v17)) == False,
	(pM_hosting(pM_pm1, vM_v20)) == False,
	(pM_near(pM_pm2, pM_pm1)) == False,
	(pM_near(pM_pm2, pM_pm2)) == True,
	(pM_near(pM_pm2, pM_pm3)) == True,
	(pM_near(pM_pm2, pM_pm4)) == False,
	(pM_near(pM_pm2, pM_pm5)) == False,
	(pM_near(pM_pm2, pM_pm6)) == False,
	(pM_near(pM_pm2, pM_pm7)) == False,
	(pM_near(pM_pm2, pM_pm8)) == False,
	(pM_near(pM_pm2, pM_pm9)) == False,
	(pM_near(pM_pm2, pM_pm10)) == False,
	(pM_bit64(pM_pm2)) == (True),
	(pM_tpLimit(pM_pm2)) == (10),
	(pM_mem(pM_pm2)) == (8),
	(pM_stable(pM_pm2)) == (False),
	(pM_core(pM_pm2)) == (8),
	(pM_hosting(pM_pm2, vM_v1)) == False,
	(pM_hosting(pM_pm2, vM_v2)) == False,
	(pM_hosting(pM_pm2, vM_v3)) == False,
	(pM_hosting(pM_pm2, vM_v4)) == False,
	(pM_hosting(pM_pm2, vM_v5)) == False,
	(pM_hosting(pM_pm2, vM_v6)) == False,
	(pM_hosting(pM_pm2, vM_v7)) == False,
	(pM_hosting(pM_pm2, vM_v8)) == False,
	(pM_hosting(pM_pm2, vM_v12)) == False,
	(pM_hosting(pM_pm2, vM_v13)) == False,
	(pM_hosting(pM_pm2, vM_v14)) == False,
	(pM_hosting(pM_pm2, vM_v15)) == False,
	(pM_hosting(pM_pm2, vM_v16)) == False,
	(pM_hosting(pM_pm2, vM_v17)) == False,
	(pM_hosting(pM_pm2, vM_v20)) == False,
	(pM_near(pM_pm3, pM_pm1)) == False,
	(pM_near(pM_pm3, pM_pm2)) == True,
	(pM_near(pM_pm3, pM_pm3)) == True,
	(pM_near(pM_pm3, pM_pm4)) == False,
	(pM_near(pM_pm3, pM_pm5)) == False,
	(pM_near(pM_pm3, pM_pm6)) == False,
	(pM_near(pM_pm3, pM_pm7)) == False,
	(pM_near(pM_pm3, pM_pm8)) == False,
	(pM_near(pM_pm3, pM_pm9)) == False,
	(pM_near(pM_pm3, pM_pm10)) == False,
	(pM_bit64(pM_pm3)) == (True),
	(pM_tpLimit(pM_pm3)) == (5),
	(pM_mem(pM_pm3)) == (16),
	(pM_stable(pM_pm3)) == (True),
	(pM_core(pM_pm3)) == (4),
	(pM_hosting(pM_pm3, vM_v1)) == False,
	(pM_hosting(pM_pm3, vM_v2)) == False,
	(pM_hosting(pM_pm3, vM_v3)) == False,
	(pM_hosting(pM_pm3, vM_v4)) == False,
	(pM_hosting(pM_pm3, vM_v5)) == False,
	(pM_hosting(pM_pm3, vM_v6)) == False,
	(pM_hosting(pM_pm3, vM_v7)) == False,
	(pM_hosting(pM_pm3, vM_v8)) == False,
	(pM_hosting(pM_pm3, vM_v12)) == False,
	(pM_hosting(pM_pm3, vM_v13)) == False,
	(pM_hosting(pM_pm3, vM_v14)) == False,
	(pM_hosting(pM_pm3, vM_v15)) == False,
	(pM_hosting(pM_pm3, vM_v16)) == False,
	(pM_hosting(pM_pm3, vM_v17)) == False,
	(pM_hosting(pM_pm3, vM_v20)) == False,
	(pM_near(pM_pm4, pM_pm1)) == False,
	(pM_near(pM_pm4, pM_pm2)) == False,
	(pM_near(pM_pm4, pM_pm3)) == False,
	(pM_near(pM_pm4, pM_pm4)) == True,
	(pM_near(pM_pm4, pM_pm5)) == True,
	(pM_near(pM_pm4, pM_pm6)) == False,
	(pM_near(pM_pm4, pM_pm7)) == False,
	(pM_near(pM_pm4, pM_pm8)) == False,
	(pM_near(pM_pm4, pM_pm9)) == False,
	(pM_near(pM_pm4, pM_pm10)) == False,
	(pM_bit64(pM_pm4)) == (False),
	(pM_tpLimit(pM_pm4)) == (20),
	(pM_mem(pM_pm4)) == (4),
	(pM_stable(pM_pm4)) == (False),
	(pM_core(pM_pm4)) == (4),
	(pM_hosting(pM_pm4, vM_v1)) == False,
	(pM_hosting(pM_pm4, vM_v2)) == False,
	(pM_hosting(pM_pm4, vM_v3)) == False,
	(pM_hosting(pM_pm4, vM_v4)) == False,
	(pM_hosting(pM_pm4, vM_v5)) == False,
	(pM_hosting(pM_pm4, vM_v6)) == False,
	(pM_hosting(pM_pm4, vM_v7)) == False,
	(pM_hosting(pM_pm4, vM_v8)) == False,
	(pM_hosting(pM_pm4, vM_v12)) == False,
	(pM_hosting(pM_pm4, vM_v13)) == False,
	(pM_hosting(pM_pm4, vM_v14)) == False,
	(pM_hosting(pM_pm4, vM_v15)) == False,
	(pM_hosting(pM_pm4, vM_v16)) == False,
	(pM_hosting(pM_pm4, vM_v17)) == False,
	(pM_hosting(pM_pm4, vM_v20)) == False,
	(pM_near(pM_pm5, pM_pm1)) == False,
	(pM_near(pM_pm5, pM_pm2)) == False,
	(pM_near(pM_pm5, pM_pm3)) == False,
	(pM_near(pM_pm5, pM_pm4)) == True,
	(pM_near(pM_pm5, pM_pm5)) == True,
	(pM_near(pM_pm5, pM_pm6)) == False,
	(pM_near(pM_pm5, pM_pm7)) == False,
	(pM_near(pM_pm5, pM_pm8)) == False,
	(pM_near(pM_pm5, pM_pm9)) == False,
	(pM_near(pM_pm5, pM_pm10)) == False,
	(pM_bit64(pM_pm5)) == (False),
	(pM_tpLimit(pM_pm5)) == (10),
	(pM_mem(pM_pm5)) == (4),
	(pM_stable(pM_pm5)) == (True),
	(pM_core(pM_pm5)) == (4),
	(pM_hosting(pM_pm5, vM_v1)) == False,
	(pM_hosting(pM_pm5, vM_v2)) == False,
	(pM_hosting(pM_pm5, vM_v3)) == False,
	(pM_hosting(pM_pm5, vM_v4)) == False,
	(pM_hosting(pM_pm5, vM_v5)) == False,
	(pM_hosting(pM_pm5, vM_v6)) == False,
	(pM_hosting(pM_pm5, vM_v7)) == False,
	(pM_hosting(pM_pm5, vM_v8)) == False,
	(pM_hosting(pM_pm5, vM_v12)) == False,
	(pM_hosting(pM_pm5, vM_v13)) == False,
	(pM_hosting(pM_pm5, vM_v14)) == False,
	(pM_hosting(pM_pm5, vM_v15)) == False,
	(pM_hosting(pM_pm5, vM_v16)) == False,
	(pM_hosting(pM_pm5, vM_v17)) == False,
	(pM_hosting(pM_pm5, vM_v20)) == False,
	(pM_near(pM_pm6, pM_pm1)) == False,
	(pM_near(pM_pm6, pM_pm2)) == False,
	(pM_near(pM_pm6, pM_pm3)) == False,
	(pM_near(pM_pm6, pM_pm4)) == False,
	(pM_near(pM_pm6, pM_pm5)) == False,
	(pM_near(pM_pm6, pM_pm6)) == True,
	(pM_near(pM_pm6, pM_pm7)) == False,
	(pM_near(pM_pm6, pM_pm8)) == False,
	(pM_near(pM_pm6, pM_pm9)) == False,
	(pM_near(pM_pm6, pM_pm10)) == False,
	(pM_bit64(pM_pm6)) == (True),
	(pM_tpLimit(pM_pm6)) == (10),
	(pM_mem(pM_pm6)) == (4),
	(pM_stable(pM_pm6)) == (False),
	(pM_core(pM_pm6)) == (4),
	(pM_hosting(pM_pm6, vM_v1)) == False,
	(pM_hosting(pM_pm6, vM_v2)) == False,
	(pM_hosting(pM_pm6, vM_v3)) == False,
	(pM_hosting(pM_pm6, vM_v4)) == False,
	(pM_hosting(pM_pm6, vM_v5)) == False,
	(pM_hosting(pM_pm6, vM_v6)) == False,
	(pM_hosting(pM_pm6, vM_v7)) == False,
	(pM_hosting(pM_pm6, vM_v8)) == False,
	(pM_hosting(pM_pm6, vM_v12)) == False,
	(pM_hosting(pM_pm6, vM_v13)) == False,
	(pM_hosting(pM_pm6, vM_v14)) == False,
	(pM_hosting(pM_pm6, vM_v15)) == False,
	(pM_hosting(pM_pm6, vM_v16)) == False,
	(pM_hosting(pM_pm6, vM_v17)) == False,
	(pM_hosting(pM_pm6, vM_v20)) == False,
	(pM_near(pM_pm7, pM_pm1)) == False,
	(pM_near(pM_pm7, pM_pm2)) == False,
	(pM_near(pM_pm7, pM_pm3)) == False,
	(pM_near(pM_pm7, pM_pm4)) == False,
	(pM_near(pM_pm7, pM_pm5)) == False,
	(pM_near(pM_pm7, pM_pm6)) == False,
	(pM_near(pM_pm7, pM_pm7)) == True,
	(pM_near(pM_pm7, pM_pm8)) == True,
	(pM_near(pM_pm7, pM_pm9)) == False,
	(pM_near(pM_pm7, pM_pm10)) == False,
	(pM_bit64(pM_pm7)) == (True),
	(pM_tpLimit(pM_pm7)) == (10),
	(pM_mem(pM_pm7)) == (8),
	(pM_stable(pM_pm7)) == (False),
	(pM_core(pM_pm7)) == (8),
	(pM_hosting(pM_pm7, vM_v1)) == False,
	(pM_hosting(pM_pm7, vM_v2)) == False,
	(pM_hosting(pM_pm7, vM_v3)) == False,
	(pM_hosting(pM_pm7, vM_v4)) == False,
	(pM_hosting(pM_pm7, vM_v5)) == False,
	(pM_hosting(pM_pm7, vM_v6)) == False,
	(pM_hosting(pM_pm7, vM_v7)) == False,
	(pM_hosting(pM_pm7, vM_v8)) == False,
	(pM_hosting(pM_pm7, vM_v12)) == False,
	(pM_hosting(pM_pm7, vM_v13)) == False,
	(pM_hosting(pM_pm7, vM_v14)) == False,
	(pM_hosting(pM_pm7, vM_v15)) == False,
	(pM_hosting(pM_pm7, vM_v16)) == False,
	(pM_hosting(pM_pm7, vM_v17)) == False,
	(pM_hosting(pM_pm7, vM_v20)) == False,
	(pM_near(pM_pm8, pM_pm1)) == False,
	(pM_near(pM_pm8, pM_pm2)) == False,
	(pM_near(pM_pm8, pM_pm3)) == False,
	(pM_near(pM_pm8, pM_pm4)) == False,
	(pM_near(pM_pm8, pM_pm5)) == False,
	(pM_near(pM_pm8, pM_pm6)) == False,
	(pM_near(pM_pm8, pM_pm7)) == True,
	(pM_near(pM_pm8, pM_pm8)) == True,
	(pM_near(pM_pm8, pM_pm9)) == False,
	(pM_near(pM_pm8, pM_pm10)) == False,
	(pM_bit64(pM_pm8)) == (True),
	(pM_tpLimit(pM_pm8)) == (5),
	(pM_mem(pM_pm8)) == (16),
	(pM_stable(pM_pm8)) == (True),
	(pM_core(pM_pm8)) == (4),
	(pM_hosting(pM_pm8, vM_v1)) == False,
	(pM_hosting(pM_pm8, vM_v2)) == False,
	(pM_hosting(pM_pm8, vM_v3)) == False,
	(pM_hosting(pM_pm8, vM_v4)) == False,
	(pM_hosting(pM_pm8, vM_v5)) == False,
	(pM_hosting(pM_pm8, vM_v6)) == False,
	(pM_hosting(pM_pm8, vM_v7)) == False,
	(pM_hosting(pM_pm8, vM_v8)) == False,
	(pM_hosting(pM_pm8, vM_v12)) == False,
	(pM_hosting(pM_pm8, vM_v13)) == False,
	(pM_hosting(pM_pm8, vM_v14)) == False,
	(pM_hosting(pM_pm8, vM_v15)) == False,
	(pM_hosting(pM_pm8, vM_v16)) == False,
	(pM_hosting(pM_pm8, vM_v17)) == False,
	(pM_hosting(pM_pm8, vM_v20)) == False,
	(pM_near(pM_pm9, pM_pm1)) == False,
	(pM_near(pM_pm9, pM_pm2)) == False,
	(pM_near(pM_pm9, pM_pm3)) == False,
	(pM_near(pM_pm9, pM_pm4)) == False,
	(pM_near(pM_pm9, pM_pm5)) == False,
	(pM_near(pM_pm9, pM_pm6)) == False,
	(pM_near(pM_pm9, pM_pm7)) == False,
	(pM_near(pM_pm9, pM_pm8)) == False,
	(pM_near(pM_pm9, pM_pm9)) == True,
	(pM_near(pM_pm9, pM_pm10)) == True,
	(pM_bit64(pM_pm9)) == (False),
	(pM_tpLimit(pM_pm9)) == (20),
	(pM_mem(pM_pm9)) == (4),
	(pM_stable(pM_pm9)) == (False),
	(pM_core(pM_pm9)) == (4),
	(pM_hosting(pM_pm9, vM_v1)) == False,
	(pM_hosting(pM_pm9, vM_v2)) == False,
	(pM_hosting(pM_pm9, vM_v3)) == False,
	(pM_hosting(pM_pm9, vM_v4)) == False,
	(pM_hosting(pM_pm9, vM_v5)) == False,
	(pM_hosting(pM_pm9, vM_v6)) == False,
	(pM_hosting(pM_pm9, vM_v7)) == False,
	(pM_hosting(pM_pm9, vM_v8)) == False,
	(pM_hosting(pM_pm9, vM_v12)) == False,
	(pM_hosting(pM_pm9, vM_v13)) == False,
	(pM_hosting(pM_pm9, vM_v14)) == False,
	(pM_hosting(pM_pm9, vM_v15)) == False,
	(pM_hosting(pM_pm9, vM_v16)) == False,
	(pM_hosting(pM_pm9, vM_v17)) == False,
	(pM_hosting(pM_pm9, vM_v20)) == False,
	(pM_near(pM_pm10, pM_pm1)) == False,
	(pM_near(pM_pm10, pM_pm2)) == False,
	(pM_near(pM_pm10, pM_pm3)) == False,
	(pM_near(pM_pm10, pM_pm4)) == False,
	(pM_near(pM_pm10, pM_pm5)) == False,
	(pM_near(pM_pm10, pM_pm6)) == False,
	(pM_near(pM_pm10, pM_pm7)) == False,
	(pM_near(pM_pm10, pM_pm8)) == False,
	(pM_near(pM_pm10, pM_pm9)) == True,
	(pM_near(pM_pm10, pM_pm10)) == True,
	(pM_bit64(pM_pm10)) == (True),
	(pM_tpLimit(pM_pm10)) == (40),
	(pM_mem(pM_pm10)) == (40),
	(pM_stable(pM_pm10)) == (True),
	(pM_core(pM_pm10)) == (16),
	(pM_hosting(pM_pm10, vM_v1)) == False,
	(pM_hosting(pM_pm10, vM_v2)) == False,
	(pM_hosting(pM_pm10, vM_v3)) == False,
	(pM_hosting(pM_pm10, vM_v4)) == False,
	(pM_hosting(pM_pm10, vM_v5)) == False,
	(pM_hosting(pM_pm10, vM_v6)) == False,
	(pM_hosting(pM_pm10, vM_v7)) == False,
	(pM_hosting(pM_pm10, vM_v8)) == False,
	(pM_hosting(pM_pm10, vM_v12)) == False,
	(pM_hosting(pM_pm10, vM_v13)) == False,
	(pM_hosting(pM_pm10, vM_v14)) == False,
	(pM_hosting(pM_pm10, vM_v15)) == False,
	(pM_hosting(pM_pm10, vM_v16)) == False,
	(pM_hosting(pM_pm10, vM_v17)) == False,
	(pM_hosting(pM_pm10, vM_v20)) == False,
]

weights = [20, 20, 20, 20, 20, 10, 20, 30, 20, 60, 20, 20, 20, 20, 20, 10, 20, 20, 20, 10, 20, 30, 20, 60, 20, 20, 20, 20, 20, 20]

deps = [(0,0), (10,0), (0,2), (10,2), (1,4), (11,4), (1,6), (11,6), (1,8), (11,8), (2,10), (12,10), (2,12), (12,12), (3,14), (13,14), (5,16), (15,16), (6,18), (16,18), (6,20), (16,20), (6,22), (16,22), (7,24), (17,24), (7,26), (17,26), (9,28), (19,28)]

